- id: highscore-event-001
  name: 十王邦夫のアイドル強化月間
  produceHighScoreEventType: ProduceHighScoreEventType_Normal
  bannerAssetId: img_general_event_highscore-event_highscore-event-001-banner
  order: 1
- id: highscore-event-002
  name: ハイスコアイベント
  produceHighScoreEventType: ProduceHighScoreEventType_Normal
  bannerAssetId: img_general_event_highscore-event_highscore-event-002-banner
  order: 1
- id: highscore-event-003
  name: ハイスコアイベント
  produceHighScoreEventType: ProduceHighScoreEventType_Normal
  bannerAssetId: img_general_event_highscore-event_highscore-event-003-banner
  order: 1
- id: highscore-event-004
  name: ハイスコアイベント
  produceHighScoreEventType: ProduceHighScoreEventType_Normal
  bannerAssetId: img_general_event_highscore-event_highscore-event-004-banner
  order: 1
- id: highscorerush-event-001
  name: 十王邦夫のアイドル強化月間・改
  produceHighScoreEventType: ProduceHighScoreEventType_Rush
  bannerAssetId: img_general_event_highscorerush_highscorerush-event-001-banner
  order: 1
- id: highscorerush-event-002
  name: 十王邦夫のアイドル強化月間〜星々のきらめき〜
  produceHighScoreEventType: ProduceHighScoreEventType_Rush
  bannerAssetId: img_general_event_highscorerush_highscorerush-event-002-banner
  order: 1
- id: highscorerush-event-003
  name: 十王邦夫のアイドル強化月間〜星々のきらめき〜
  produceHighScoreEventType: ProduceHighScoreEventType_Rush
  bannerAssetId: img_general_event_highscorerush_highscorerush-event-003-banner
  order: 1
- id: highscorerush-event-004
  name: 十王邦夫のアイドル強化月間〜星々のきらめき〜
  produceHighScoreEventType: ProduceHighScoreEventType_Rush
  bannerAssetId: img_general_event_highscorerush_highscorerush-event-004-banner
  order: 1
- id: highscorerush-event-005
  name: 十王邦夫のアイドル強化月間〜星々のきらめき〜
  produceHighScoreEventType: ProduceHighScoreEventType_Rush
  bannerAssetId: img_general_event_highscorerush_highscorerush-event-005-banner
  order: 1