- actionPointQuantity: 15
  assetId: produce-1
  baseStepLevel: 1
  examSettingId: p_exam_setting-1
  gradientColor1: FFD731
  gradientColor2: FF9538
  id: produce-001
  idolCardParameterGrowthLimit: 1000
  maxProduceEventCharacterGrowthNumber: 2
  name: レギュラー
  order: 2
  produceNavigationAuditionId: p_navi-produce_group-001-audition
  produceNavigationLoseId: p_navi-produce_group-001-lose
  produceNavigationNormalId: p_navi-produce_group-001-normal
  produceSettingId: p_setting-1
  steps: 13
- actionPointQuantity: 20
  assetId: produce-2
  baseStepLevel: 5
  examSettingId: p_exam_setting-1
  gradientColor1: 72B8FF
  gradientColor2: EA74FF
  id: produce-002
  idolCardParameterGrowthLimit: 1500
  maxProduceEventCharacterGrowthNumber: 3
  name: プロ
  order: 3
  produceNavigationAuditionId: p_navi-produce_group-001-audition
  produceNavigationLoseId: p_navi-produce_group-001-lose
  produceNavigationNormalId: p_navi-produce_group-001-normal
  produceSettingId: p_setting-2
  steps: 16
  unlockConditionSetId: cd-task_clear-01-040
  viewConditionSetId: cd-pro_produce-view_open