- id: p_random_pool-all-upgrade_1
  produceCardRatios:
  - id: p_card-00-men-1_007
    upgradeCount: 1
    ratio: 1
  - id: p_card-00-men-1_005
    upgradeCount: 1
    ratio: 1
  - id: p_card-00-act-2_009
    upgradeCount: 1
    ratio: 1
  - id: p_card-00-men-2_012
    upgradeCount: 1
    ratio: 1
  - id: p_card-00-men-2_014
    upgradeCount: 1
    ratio: 1
  - id: p_card-00-men-3_011
    upgradeCount: 1
    ratio: 1
  - id: p_card-00-men-3_003
    upgradeCount: 1
    ratio: 1
  - id: p_card-00-men-3_005
    upgradeCount: 1
    ratio: 1
  - id: p_card-00-men-3_012
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-1_001
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-1_002
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-1_008
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-1_019
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-1_020
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-1_021
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-1_022
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-1_023
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-1_024
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-1_025
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-2_001
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-2_002
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-2_003
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-2_030
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-2_031
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-2_032
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-2_033
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_034
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_035
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_036
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_037
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_038
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_039
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_040
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_041
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-2_042
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_043
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-3_030
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-3_031
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-3_029
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-3_033
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-3_035
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-3_036
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-3_006
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-3_010
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-1_003
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-1_004
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-1_006
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-1_009
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-1_027
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-1_028
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-1_029
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-1_030
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-1_031
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-1_032
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-1_033
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_004
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_008
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_050
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-2_045
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-2_046
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-2_047
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-2_048
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-2_049
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_051
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_052
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_053
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_054
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_055
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_057
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_058
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-3_038
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-3_039
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_041
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_042
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_043
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_044
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_002
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_004
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-3_001
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-1_034
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_011
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-2_059
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-3_049
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-3_032
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-1_035
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_060
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_056
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-3_050
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-3_045
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-1_036
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-2_062
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-3_052
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-1_038
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-1_040
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-1_041
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-1_042
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-1_044
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-1_046
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-1_039
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-1_049
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-1_048
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-2_065
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-2_068
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-2_069
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-2_072
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-2_073
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-2_063
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-2_067
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-2_070
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-2_071
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-2_064
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-2_066
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-2_077
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-2_079
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-3_053
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-3_054
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-3_055
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-3_056
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-3_057
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-3_058
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-3_062
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-3_063
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-3_065
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-1_037
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_040
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-2_074
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-1_051
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-2_075
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-2_076
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-2_080
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-2_081
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-2_082
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-3_061
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-1_074
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-2_061
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-3_034
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-1_050
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-2_078
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-1_068
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-1_069
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-1_070
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-1_071
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-1_072
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-1_073
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_098
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_099
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_100
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_101
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-2_102
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-2_103
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-2_110
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-2_111
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-2_112
    upgradeCount: 1
    ratio: 1
- id: p_random_pool-rush_idol_unique_set-ssr-upgrade_1
  produceCardRatios:
  - id: p_card-02-ido-3_018
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_021
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_067
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_069
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_073
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_096
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_079
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_120
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_086
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_103
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_105
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_111
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_127
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_130
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_143
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_140
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-ido-3_083
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-ido-3_101
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-ido-3_110
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-ido-3_122
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-ido-3_113
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-ido-3_129
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-ido-3_131
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-ido-3_135
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-ido-3_149
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-ido-3_116
    upgradeCount: 1
    ratio: 1
- id: p_random_pool-rush-ssr-upgrade_1
  produceCardRatios:
  - id: p_card-02-ido-3_015
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_019
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_022
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_068
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_076
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_078
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-ido-3_081
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-ido-3_013
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-ido-3_016
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-ido-3_066
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-ido-3_070
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-ido-3_074
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-ido-3_075
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-ido-3_080
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-ido-3_085
    upgradeCount: 1
    ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardRatios:
  - id: p_card-00-men-3_011
    upgradeCount: 1
    ratio: 1
  - id: p_card-00-men-3_003
    upgradeCount: 1
    ratio: 1
  - id: p_card-00-men-3_005
    upgradeCount: 1
    ratio: 1
  - id: p_card-00-men-3_012
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-3_030
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-3_031
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-3_029
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-3_033
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-3_035
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-3_036
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-3_006
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-3_010
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-3_038
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-3_039
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_041
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_042
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_043
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_044
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_002
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_004
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-3_001
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-3_049
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-act-3_032
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-3_050
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-3_045
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-act-3_052
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-3_053
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-3_054
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-3_055
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-3_056
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-3_057
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-3_058
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-3_062
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-3_063
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-act-3_065
    upgradeCount: 1
    ratio: 1
  - id: p_card-02-men-3_040
    upgradeCount: 1
    ratio: 1
  - id: p_card-03-men-3_061
    upgradeCount: 1
    ratio: 1
  - id: p_card-01-men-3_034
    upgradeCount: 1
    ratio: 1