- beforeProduceCardId: p_card-01-act-1_019
  afterProduceCardId: p_card-01-act-1_069
  conditionSetId: cd_producer_level-052
  isNotReward: true
  order: 2101052
- beforeProduceCardId: p_card-01-act-2_002
  afterProduceCardId: p_card-01-men-2_110
  conditionSetId: cd_producer_level-056
  isNotReward: true
  order: 3101056
- beforeProduceCardId: p_card-01-act-2_003
  afterProduceCardId: p_card-01-men-2_098
  conditionSetId: cd_producer_level-054
  isNotReward: true
  order: 3101054
- beforeProduceCardId: p_card-01-men-1_024
  afterProduceCardId: p_card-01-act-1_068
  conditionSetId: cd_producer_level-051
  isNotReward: true
  order: 2201051
- beforeProduceCardId: p_card-01-men-2_039
  afterProduceCardId: p_card-01-men-2_099
  conditionSetId: cd_producer_level-053
  isNotReward: true
  order: 3201053
- beforeProduceCardId: p_card-02-act-1_027
  afterProduceCardId: p_card-02-act-1_070
  conditionSetId: cd_producer_level-051
  isNotReward: true
  order: 2102051
- beforeProduceCardId: p_card-02-act-1_029
  afterProduceCardId: p_card-02-act-1_071
  conditionSetId: cd_producer_level-052
  isNotReward: true
  order: 2102052
- beforeProduceCardId: p_card-02-act-2_045
  afterProduceCardId: p_card-02-men-2_100
  conditionSetId: cd_producer_level-054
  isNotReward: true
  order: 3102054
- beforeProduceCardId: p_card-02-men-2_050
  afterProduceCardId: p_card-02-men-2_101
  conditionSetId: cd_producer_level-053
  isNotReward: true
  order: 3202053
- beforeProduceCardId: p_card-02-men-2_053
  afterProduceCardId: p_card-02-men-2_111
  conditionSetId: cd_producer_level-057
  isNotReward: true
  order: 3202057
- beforeProduceCardId: p_card-03-act-1_041
  afterProduceCardId: p_card-03-act-1_073
  conditionSetId: cd_producer_level-052
  isNotReward: true
  order: 2103052
- beforeProduceCardId: p_card-03-act-1_046
  afterProduceCardId: p_card-03-act-1_072
  conditionSetId: cd_producer_level-051
  isNotReward: true
  order: 2103051
- beforeProduceCardId: p_card-03-act-2_065
  afterProduceCardId: p_card-03-men-2_112
  conditionSetId: cd_producer_level-053
  isNotReward: true
  order: 3103053
- beforeProduceCardId: p_card-03-act-2_068
  afterProduceCardId: p_card-03-act-2_102
  conditionSetId: cd_producer_level-058
  isNotReward: true
  order: 3103058
- beforeProduceCardId: p_card-03-act-2_069
  afterProduceCardId: p_card-03-men-2_103
  conditionSetId: cd_producer_level-054
  isNotReward: true
  order: 3103054