- id: produce-001
  name: レギュラー
  baseStepLevel: 1
  maxRefreshCount: 0
  produceSelectScreenOrderType: ProduceSelectScreenOrderType_First
  challengeViewConditionSetId: ""
  viewConditionSetId: ""
  unlockConditionSetId: ""
  examSettingId: p_exam_setting-1
  produceSettingId: p_setting-1
  idolCardParameterGrowthLimit: 1000
  maxProduceEventCharacterGrowthNumber: 2
  steps: 13
  actionPointQuantity: 15
  assetId: produce-1
  produceNavigationNormalId: p_navi-produce_group-001-normal
  produceNavigationAuditionId: p_navi-produce_group-001-audition
  produceNavigationLoseId: p_navi-produce_group-001-lose
  gradientColor1: FFD731
  gradientColor2: FF9538
  order: 2
- id: produce-002
  name: プロ
  baseStepLevel: 5
  maxRefreshCount: 0
  produceSelectScreenOrderType: ProduceSelectScreenOrderType_First
  challengeViewConditionSetId: ""
  viewConditionSetId: cd-pro_produce-view_open
  unlockConditionSetId: cd-task_clear-01-040
  examSettingId: p_exam_setting-1
  produceSettingId: p_setting-2
  idolCardParameterGrowthLimit: 1500
  maxProduceEventCharacterGrowthNumber: 3
  steps: 16
  actionPointQuantity: 20
  assetId: produce-2
  produceNavigationNormalId: p_navi-produce_group-001-normal
  produceNavigationAuditionId: p_navi-produce_group-001-audition
  produceNavigationLoseId: p_navi-produce_group-001-lose
  gradientColor1: 72B8FF
  gradientColor2: EA74FF
  order: 3
- id: produce-003
  name: マスター
  baseStepLevel: 5
  maxRefreshCount: 0
  produceSelectScreenOrderType: ProduceSelectScreenOrderType_First
  challengeViewConditionSetId: cd-master_produce-view_open
  viewConditionSetId: cd-master_produce-view_open
  unlockConditionSetId: cd-master_produce-unlock_open
  examSettingId: p_exam_setting-1
  produceSettingId: p_setting-3
  idolCardParameterGrowthLimit: 1800
  maxProduceEventCharacterGrowthNumber: 3
  steps: 18
  actionPointQuantity: 20
  assetId: produce-3
  produceNavigationNormalId: p_navi-produce_group-001-normal
  produceNavigationAuditionId: p_navi-produce_group-001-audition
  produceNavigationLoseId: p_navi-produce_group-001-lose
  gradientColor1: FF1C7E
  gradientColor2: FFC436
  order: 4
- id: produce-004
  name: プロ
  baseStepLevel: 1
  maxRefreshCount: 4
  produceSelectScreenOrderType: ProduceSelectScreenOrderType_First
  challengeViewConditionSetId: ""
  viewConditionSetId: ""
  unlockConditionSetId: cd-nia_produce-unlock_open
  examSettingId: p_exam_setting-1
  produceSettingId: p_setting-4
  idolCardParameterGrowthLimit: 2000
  maxProduceEventCharacterGrowthNumber: 0
  steps: 27
  actionPointQuantity: 20
  assetId: produce-nia
  produceNavigationNormalId: p_navi-produce_group-002-normal
  produceNavigationAuditionId: p_navi-produce_group-002-audition
  produceNavigationLoseId: p_navi-produce_group-002-lose
  gradientColor1: 72B8FF
  gradientColor2: EA74FF
  order: 1
- id: produce-005
  name: マスター
  baseStepLevel: 1
  maxRefreshCount: 4
  produceSelectScreenOrderType: ProduceSelectScreenOrderType_First
  challengeViewConditionSetId: cd-nia_produce-unlock_open
  viewConditionSetId: ""
  unlockConditionSetId: cd-nia_master_produce-unlock_open
  examSettingId: p_exam_setting-1
  produceSettingId: p_setting-5
  idolCardParameterGrowthLimit: 2300
  maxProduceEventCharacterGrowthNumber: 0
  steps: 26
  actionPointQuantity: 20
  assetId: produce-nia-2
  produceNavigationNormalId: p_navi-produce_group-002-normal
  produceNavigationAuditionId: p_navi-produce_group-002-audition
  produceNavigationLoseId: p_navi-produce_group-002-lose
  gradientColor1: FF1C7E
  gradientColor2: FFC436
  order: 2