- produceId: produce-001
  characterId: amao
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-001
  characterId: atbm
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_atbm_produce-character-open
- produceId: produce-001
  characterId: fktn
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-001
  characterId: hmsz
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-001
  characterId: hrnm
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-001
  characterId: hski
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-001
  characterId: hume
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-001
  characterId: jsna
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-001
  characterId: kcna
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-001
  characterId: kllj
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-001
  characterId: shro
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-001
  characterId: ssmk
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-001
  characterId: ttmr
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-002
  characterId: amao
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-002
  characterId: atbm
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_atbm_produce-character-open
- produceId: produce-002
  characterId: fktn
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-002
  characterId: hmsz
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-002
  characterId: hrnm
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-002
  characterId: hski
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-002
  characterId: hume
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-002
  characterId: jsna
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-002
  characterId: kcna
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-002
  characterId: kllj
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-002
  characterId: shro
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-002
  characterId: ssmk
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-002
  characterId: ttmr
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-003
  characterId: amao
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-003
  characterId: atbm
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_atbm_produce-character-open
- produceId: produce-003
  characterId: fktn
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-003
  characterId: hmsz
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-003
  characterId: hrnm
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-003
  characterId: hski
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-003
  characterId: hume
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-003
  characterId: jsna
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-003
  characterId: kcna
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-003
  characterId: kllj
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-003
  characterId: shro
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-003
  characterId: ssmk
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-003
  characterId: ttmr
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd_time_24_0516_produce-character-open
- produceId: produce-004
  characterId: amao
  forceLiveCommonIdolCardId: i_card-amao-3-007
  unlockConditionSetId: cd-dearness_level-amao-10
- produceId: produce-004
  characterId: atbm
  forceLiveCommonIdolCardId: i_card-atbm-3-012
  unlockConditionSetId: cd-dearness_level-atbm-10
- produceId: produce-004
  characterId: fktn
  forceLiveCommonIdolCardId: i_card-fktn-3-007
  unlockConditionSetId: cd-dearness_level-fktn-10
- produceId: produce-004
  characterId: hmsz
  forceLiveCommonIdolCardId: i_card-hmsz-3-005
  unlockConditionSetId: cd-dearness_level-hmsz-10
- produceId: produce-004
  characterId: hrnm
  forceLiveCommonIdolCardId: i_card-hrnm-3-007
  unlockConditionSetId: cd-dearness_level-hrnm-10
- produceId: produce-004
  characterId: hski
  forceLiveCommonIdolCardId: i_card-hski-3-008
  unlockConditionSetId: cd-dearness_level-hski-10
- produceId: produce-004
  characterId: hume
  forceLiveCommonIdolCardId: i_card-hume-3-006
  unlockConditionSetId: cd-dearness_level-hume-10
- produceId: produce-004
  characterId: jsna
  forceLiveCommonIdolCardId: i_card-jsna-3-002
  unlockConditionSetId: cd-dearness_level-jsna-10
- produceId: produce-004
  characterId: kcna
  forceLiveCommonIdolCardId: i_card-kcna-3-007
  unlockConditionSetId: cd-dearness_level-kcna-10
- produceId: produce-004
  characterId: kllj
  forceLiveCommonIdolCardId: i_card-kllj-3-006
  unlockConditionSetId: cd-dearness_level-kllj-10
- produceId: produce-004
  characterId: shro
  forceLiveCommonIdolCardId: i_card-shro-3-007
  unlockConditionSetId: cd-dearness_level-shro-10
- produceId: produce-004
  characterId: ssmk
  forceLiveCommonIdolCardId: i_card-ssmk-3-007
  unlockConditionSetId: cd-dearness_level-ssmk-10
- produceId: produce-004
  characterId: ttmr
  forceLiveCommonIdolCardId: i_card-ttmr-3-007
  unlockConditionSetId: cd-dearness_level-ttmr-10
- produceId: produce-005
  characterId: amao
  forceLiveCommonIdolCardId: i_card-amao-3-007
  unlockConditionSetId: cd-dearness_level-amao-20
- produceId: produce-005
  characterId: atbm
  forceLiveCommonIdolCardId: i_card-atbm-3-012
  unlockConditionSetId: cd-dearness_level-atbm-20
- produceId: produce-005
  characterId: fktn
  forceLiveCommonIdolCardId: i_card-fktn-3-007
  unlockConditionSetId: cd-dearness_level-fktn-20
- produceId: produce-005
  characterId: hmsz
  forceLiveCommonIdolCardId: i_card-hmsz-3-005
  unlockConditionSetId: cd-dearness_level-hmsz-20
- produceId: produce-005
  characterId: hrnm
  forceLiveCommonIdolCardId: i_card-hrnm-3-007
  unlockConditionSetId: cd-dearness_level-hrnm-20
- produceId: produce-005
  characterId: hski
  forceLiveCommonIdolCardId: i_card-hski-3-008
  unlockConditionSetId: cd-dearness_level-hski-20
- produceId: produce-005
  characterId: hume
  forceLiveCommonIdolCardId: i_card-hume-3-006
  unlockConditionSetId: cd-dearness_level-hume-20
- produceId: produce-005
  characterId: jsna
  forceLiveCommonIdolCardId: i_card-jsna-3-002
  unlockConditionSetId: cd-dearness_level-jsna-20
- produceId: produce-005
  characterId: kcna
  forceLiveCommonIdolCardId: i_card-kcna-3-007
  unlockConditionSetId: cd-dearness_level-kcna-20
- produceId: produce-005
  characterId: kllj
  forceLiveCommonIdolCardId: i_card-kllj-3-006
  unlockConditionSetId: cd-dearness_level-kllj-20
- produceId: produce-005
  characterId: shro
  forceLiveCommonIdolCardId: i_card-shro-3-007
  unlockConditionSetId: cd-dearness_level-shro-20
- produceId: produce-005
  characterId: ssmk
  forceLiveCommonIdolCardId: i_card-ssmk-3-007
  unlockConditionSetId: cd-dearness_level-ssmk-20
- produceId: produce-005
  characterId: ttmr
  forceLiveCommonIdolCardId: i_card-ttmr-3-007
  unlockConditionSetId: cd-dearness_level-ttmr-20
- produceId: produce-006
  characterId: amao
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-amao-10
- produceId: produce-006
  characterId: atbm
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-atbm-10
- produceId: produce-006
  characterId: fktn
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-fktn-10
- produceId: produce-006
  characterId: hmsz
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-hmsz-10
- produceId: produce-006
  characterId: hrnm
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-hrnm-10
- produceId: produce-006
  characterId: hski
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-hski-10
- produceId: produce-006
  characterId: hume
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-hume-10
- produceId: produce-006
  characterId: jsna
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-jsna-10
- produceId: produce-006
  characterId: kcna
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-kcna-10
- produceId: produce-006
  characterId: kllj
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-kllj-10
- produceId: produce-006
  characterId: shro
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-shro-10
- produceId: produce-006
  characterId: ssmk
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-ssmk-10
- produceId: produce-006
  characterId: ttmr
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-ttmr-10