- id: p_trigger-buy_shop_item_produce_drink
  phaseType: ProducePhaseType_BuyShopItemProduceDrink
- id: p_trigger-change_produce_card
  phaseType: ProducePhaseType_ChangeProduceCard
- id: p_trigger-customize_produce_card
  phaseType: ProducePhaseType_CustomizeProduceCard
- id: p_trigger-delete_produce_card-0000_0000-p_card_search-active_skill-deck_all
  phaseType: ProducePhaseType_DeleteProduceCard
- id: p_trigger-delete_produce_card-0000_0000-p_card_search-deck_all
  phaseType: ProducePhaseType_DeleteProduceCard
- id: p_trigger-delete_produce_card-0000_0000-p_card_search-mental_skill-deck_all
  phaseType: ProducePhaseType_DeleteProduceCard
- id: p_trigger-end_audition
  phaseType: ProducePhaseType_EndAudition
- id: p_trigger-end_before_audition_refresh-dance-0400_0000
  phaseType: ProducePhaseType_EndBeforeAuditionRefresh
- id: p_trigger-end_before_audition_refresh-for_nia_master
  phaseType: ProducePhaseType_EndBeforeAuditionRefresh
- id: p_trigger-end_before_audition_refresh-produce_card_count-0022_0000-for_nia_master
  phaseType: ProducePhaseType_EndBeforeAuditionRefresh
- id: p_trigger-end_before_audition_refresh-visual-0400_0000
  phaseType: ProducePhaseType_EndBeforeAuditionRefresh
- id: p_trigger-end_before_audition_refresh-vocal-0400_0000
  phaseType: ProducePhaseType_EndBeforeAuditionRefresh
- id: p_trigger-end_lesson_before_present-lesson
  phaseType: ProducePhaseType_EndLessonBeforePresent
- id: p_trigger-end_lesson_before_present-lesson_dance
  phaseType: ProducePhaseType_EndLessonBeforePresent
- id: p_trigger-end_lesson_before_present-lesson_dance_sp
  phaseType: ProducePhaseType_EndLessonBeforePresent
- id: p_trigger-end_lesson_before_present-lesson_visual
  phaseType: ProducePhaseType_EndLessonBeforePresent
- id: p_trigger-end_lesson_before_present-lesson_visual_sp
  phaseType: ProducePhaseType_EndLessonBeforePresent
- id: p_trigger-end_lesson_before_present-lesson_vocal
  phaseType: ProducePhaseType_EndLessonBeforePresent
- id: p_trigger-end_lesson_before_present-lesson_vocal_sp
  phaseType: ProducePhaseType_EndLessonBeforePresent
- id: p_trigger-end_lesson-lesson
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_dance
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_dance_normal
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_dance_sp
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_dance_sp-dance-0400_0000
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_dance_sp-stamina_ratio-0000_0800
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_dance-dance-0700_0000
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_dance-stamina_ratio-0000_0800
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_dance-stamina_ratio-0500_0000
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_hard
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_hard-dance-0400_0000
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_hard-visual-0400_0000
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_hard-vocal-0400_0000
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_sp
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_sp-stamina_ratio-0000_0800
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_sp-stamina_ratio-0500_0000
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_sp-vocal-0400_0000
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_visual
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_visual_normal
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_visual_sp
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_visual_sp-stamina_ratio-0000_0800
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_visual_sp-visual-0400_0000
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_visual-stamina_ratio-0000_0800
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_visual-stamina_ratio-0500_0000
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_vocal
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_vocal_normal
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_vocal_sp
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_vocal_sp-stamina_ratio-0000_0800
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_vocal_sp-vocal-0400_0000
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_vocal-stamina_ratio-0000_0800
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson_vocal-stamina_ratio-0500_0000
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_lesson-lesson-stamina_ratio-0000_0999
  phaseType: ProducePhaseType_EndLesson
- id: p_trigger-end_present-for_nia_master
  phaseType: ProducePhaseType_EndPresent
- id: p_trigger-end_shop-for_nia_master
  phaseType: ProducePhaseType_EndShop
- id: p_trigger-end_step_event_activity
  phaseType: ProducePhaseType_EndStepEventActivity
- id: p_trigger-end_step_event_activity-for_nia_master
  phaseType: ProducePhaseType_EndStepEventActivity
- id: p_trigger-end_step_event_activity-visual-0400_0000
  phaseType: ProducePhaseType_EndStepEventActivity
- id: p_trigger-end_step_event_business-produce_card
  phaseType: ProducePhaseType_EndStepEventBusiness
- id: p_trigger-end_step_event_business-produce_drink
  phaseType: ProducePhaseType_EndStepEventBusiness
- id: p_trigger-end_step_event_business-produce_point
  phaseType: ProducePhaseType_EndStepEventBusiness
- id: p_trigger-end_step_event_business-stamina
  phaseType: ProducePhaseType_EndStepEventBusiness
- id: p_trigger-end_step_event_school
  phaseType: ProducePhaseType_EndStepEventSchool
- id: p_trigger-end_step_event_school-dance-0400_0000
  phaseType: ProducePhaseType_EndStepEventSchool
- id: p_trigger-end_step_event_school-visual-0700_0000
  phaseType: ProducePhaseType_EndStepEventSchool
- id: p_trigger-get_produce_card-0000_0000-p_card_search-active_skill-deck_all
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_block-000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_block-000-visual-0200_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_card_play_aggressive-000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_card_play_aggressive-000-stamina_ratio-0500_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_card_play_aggressive-000-visual-0400_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_concentration-000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_concentration-000-effect_group-visible-exam_preservation-000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_concentration-000-stamina_ratio-0500_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_full_power-000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_full_power-000-effect_group-visible-exam_preservation-000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_full_power-000-stamina_ratio-0500_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_lesson_buff-000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_lesson_buff-000-stamina_ratio-0500_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_parameter_buff-000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_parameter_buff-000-dance-0200_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_parameter_buff-000-dance-0700_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_parameter_buff-000-stamina_ratio-0500_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_preservation-000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_preservation-000-vocal-0400_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_review-000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_review-000-dance-0700_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_review-000-stamina_ratio-0500_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_review-000-visual-0200_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_review-000-visual-0700_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_review-000-vocal-0700_0000
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_card-0000_0000-p_card_search-mental_skill-deck_all
  phaseType: ProducePhaseType_GetProduceCard
- id: p_trigger-get_produce_drink
  phaseType: ProducePhaseType_GetProduceDrink
- id: p_trigger-none-stamina_ratio-0000_0800
  phaseType: ProducePhaseType_Unknown
- id: p_trigger-produce_start
  phaseType: ProducePhaseType_ProduceStart
- id: p_trigger-produce_start-initial
  phaseType: ProducePhaseType_ProduceStart
- id: p_trigger-produce_start-no_description
  phaseType: ProducePhaseType_ProduceStart
- id: p_trigger-start_audition_final
  phaseType: ProducePhaseType_StartAuditionFinal
- id: p_trigger-start_audition_mid1
  phaseType: ProducePhaseType_StartAuditionMid1
- id: p_trigger-start_audition_mid2
  phaseType: ProducePhaseType_StartAuditionMid2
- id: p_trigger-start_customize
  phaseType: ProducePhaseType_StartCustomize
- id: p_trigger-start_customize-for_nia_master
  phaseType: ProducePhaseType_StartCustomize
- id: p_trigger-start_customize-visual-0200_0000
  phaseType: ProducePhaseType_StartCustomize
- id: p_trigger-start_customize-vocal-0200_0000
  phaseType: ProducePhaseType_StartCustomize
- id: p_trigger-start_lesson-lesson
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_lesson-lesson_dance
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_lesson-lesson_dance_hard
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_lesson-lesson_dance_sp
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_lesson-lesson_hard
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_lesson-lesson_sp
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_lesson-lesson_sp-stamina_ratio-0500_0000
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_lesson-lesson_visual
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_lesson-lesson_visual_hard
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_lesson-lesson_visual_sp
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_lesson-lesson_vocal
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_lesson-lesson_vocal_hard
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_lesson-lesson_vocal_sp
  phaseType: ProducePhaseType_StartLesson
- id: p_trigger-start_present
  phaseType: ProducePhaseType_StartPresent
- id: p_trigger-start_present-dance-0700_0000
  phaseType: ProducePhaseType_StartPresent
- id: p_trigger-start_present-visual-0700_0000
  phaseType: ProducePhaseType_StartPresent
- id: p_trigger-start_present-vocal-0400_0000
  phaseType: ProducePhaseType_StartPresent
- id: p_trigger-start_present-vocal-0700_0000
  phaseType: ProducePhaseType_StartPresent
- id: p_trigger-start_refresh
  phaseType: ProducePhaseType_StartRefresh
- id: p_trigger-start_shop
  phaseType: ProducePhaseType_StartShop
- id: p_trigger-start_shop-dance-0700_0000
  phaseType: ProducePhaseType_StartShop
- id: p_trigger-start_shop-no_description
  phaseType: ProducePhaseType_StartShop
- id: p_trigger-upgrade_produce_card-0000_0000-p_card_search-active_skill-deck_all
  phaseType: ProducePhaseType_UpgradeProduceCard
- id: p_trigger-upgrade_produce_card-0000_0000-p_card_search-deck_all
  phaseType: ProducePhaseType_UpgradeProduceCard
- id: p_trigger-upgrade_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_parameter_buff-000-dance-0700_0000
  phaseType: ProducePhaseType_UpgradeProduceCard
- id: p_trigger-upgrade_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_preservation-000-visual-0700_0000
  phaseType: ProducePhaseType_UpgradeProduceCard
- id: p_trigger-upgrade_produce_card-0000_0000-p_card_search-deck_all-effect_group-visible-exam_review-000-vocal-0700_0000
  phaseType: ProducePhaseType_UpgradeProduceCard
- id: p_trigger-upgrade_produce_card-0000_0000-p_card_search-mental_skill-deck_all
  phaseType: ProducePhaseType_UpgradeProduceCard
- id: p_trigger-upgrade_produce_card-vocal-0400_0000
  phaseType: ProducePhaseType_UpgradeProduceCard