- id: producer_ranking_produce-000
  produceId: produce-004
- id: producer_ranking_produce-000
  produceId: produce-005
- id: producer_ranking_produce-001
  produceId: produce-004
- id: producer_ranking_produce-001
  produceId: produce-005
- id: producer_ranking_produce-001
  produceId: produce-006