- id: produce_growth_panel_sheet-hif
  produceType: ProduceType_HatsuboshiIdolFestival
  unlockItemId: item-produce-produce_growth_panel_sheet_point-hif
  missionGroupId: mission-group-mission_HIF_clear_1
  achievementId: achieve-o_028