- characterId: amao
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: amao
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid2
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: amao
  produceId: produce-007
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: amao
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-01
- characterId: amao
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09
- characterId: hmsz
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hmsz
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid2
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hmsz
  produceId: produce-007
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hmsz
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-01
- characterId: hmsz
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09
- characterId: hrnm
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hrnm
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid2
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hrnm
  produceId: produce-007
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hrnm
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-01
- characterId: hrnm
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09
- characterId: hski
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hski
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid2
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hski
  produceId: produce-007
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hski
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-02
- characterId: hski
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-07
- characterId: hume
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hume
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid2
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hume
  produceId: produce-007
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hume
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-04
- characterId: hume
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09
- characterId: kcna
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: kcna
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid2
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: kcna
  produceId: produce-007
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: kcna
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-06
- characterId: kcna
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09
- characterId: kllj
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-01
- characterId: kllj
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09
- characterId: shro
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: shro
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid2
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: shro
  produceId: produce-007
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: shro
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-05
- characterId: shro
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09
- characterId: ssmk
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-01
- characterId: ssmk
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09
- characterId: ttmr
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: ttmr
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid2
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: ttmr
  produceId: produce-007
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: ttmr
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-03
- characterId: ttmr
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09