- type: ProduceExamEffectType_ExamLesson
  name: パラメータ
  swapName: スコア
  produceDescriptionId: Label_ExamLesson
  examProduceDescriptionId: Label_ExamLesson
  mainBuffMinThresholds: []
  noIcon: true
  noReference: true
- type: ProduceExamEffectType_ExamParameterBuff
  name: 好調
  swapName: 好調
  produceDescriptionId: Label_ExamParameterBuff
  examProduceDescriptionId: Label_ExamParameterBuff
  mainBuffMinThresholds:
  - 3
  - 5
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamBlock
  name: 元気
  swapName: 元気
  produceDescriptionId: Label_ExamBlock
  examProduceDescriptionId: Label_ExamBlock
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamCardDraw
  name: スキルカードを引く
  swapName: スキルカードを引く
  produceDescriptionId: Label_ExamCardDraw
  examProduceDescriptionId: Label_ExamCardDraw
  mainBuffMinThresholds: []
  noIcon: false
  noReference: true
- type: ProduceExamEffectType_ExamStaminaConsumptionDown
  name: 消費体力減少
  swapName: 消費体力減少
  produceDescriptionId: Label_ExamStaminaConsumptionDown
  examProduceDescriptionId: Label_ExamStaminaConsumptionDown
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamCardCreateId
  name: 生成
  swapName: 生成
  produceDescriptionId: Label_ExamCardCreateId
  examProduceDescriptionId: Label_ExamCardCreateId
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamStaminaReduceFix
  name: 体力消費
  swapName: 体力消費
  produceDescriptionId: Label_ExamStaminaReduceFix
  examProduceDescriptionId: Label_ExamStaminaReduceFix
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamLessonBuff
  name: 集中
  swapName: 集中
  produceDescriptionId: Label_ExamLessonBuff_Produce
  examProduceDescriptionId: Label_ExamLessonBuff_Exam
  mainBuffMinThresholds:
  - 5
  - 10
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamCardUpgrade
  name: レッスン中強化
  swapName: 試験・ステージ中強化
  produceDescriptionId: Label_ExamCardUpgrade
  examProduceDescriptionId: Label_ExamCardUpgrade
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamPlayableValueAdd
  name: スキルカード使用数追加
  swapName: スキルカード使用数追加
  produceDescriptionId: Label_ExamPlayableValueAdd_Produce
  examProduceDescriptionId: Label_ExamPlayableValueAdd_Exam
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamLessonBuffMultiple
  name: 集中効果一時増加
  swapName: 集中効果一時増加
  produceDescriptionId: Label_ExamLessonBuffMultiple
  examProduceDescriptionId: Label_ExamLessonBuffMultiple
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamCardStaminaConsumptionChange
  name: 消費体力変化
  swapName: 消費体力変化
  produceDescriptionId: Label_ExamCardStaminaConsumptionChange
  examProduceDescriptionId: Label_ExamCardStaminaConsumptionChange
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamBlockRestriction
  name: 元気増加無効
  swapName: 元気増加無効
  produceDescriptionId: Label_ExamBlockRestriction
  examProduceDescriptionId: Label_ExamBlockRestriction
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamStatusEnchant
  name: 持続効果
  swapName: 持続効果
  produceDescriptionId: Label_ExamStatusEnchant
  examProduceDescriptionId: Label_ExamStatusEnchant
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamCardStaminaConsumptionDownSpecify
  name: 消費体力低下
  swapName: 消費体力低下
  produceDescriptionId: Label_ExamCardStaminaConsumptionDownSpecify
  examProduceDescriptionId: Label_ExamCardStaminaConsumptionDownSpecify
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamStaminaDamage
  name: 体力減少
  swapName: 体力減少
  produceDescriptionId: Label_ExamStaminaDamage
  examProduceDescriptionId: Label_ExamStaminaDamage
  mainBuffMinThresholds: []
  noIcon: false
  noReference: true
- type: ProduceExamEffectType_ExamStaminaRecoverFix
  name: 体力回復
  swapName: 体力回復
  produceDescriptionId: Label_ExamStaminaRecoverFix
  examProduceDescriptionId: Label_ExamStaminaRecoverFix
  mainBuffMinThresholds: []
  noIcon: false
  noReference: true
- type: ProduceExamEffectType_ExamLessonFix
  name: 固定パラメータ
  swapName: 固定スコア
  produceDescriptionId: Label_ExamLessonFix
  examProduceDescriptionId: Label_ExamLessonFix
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamCardDuplicate
  name: 複製
  swapName: 複製
  produceDescriptionId: Label_ExamCardDuplicate
  examProduceDescriptionId: Label_ExamCardDuplicate
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamReview
  name: 好印象
  swapName: 好印象
  produceDescriptionId: Label_ExamReview_Produce
  examProduceDescriptionId: Label_ExamReview_Exam
  mainBuffMinThresholds:
  - 5
  - 10
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamCardSearchEffectPlayCountBuff
  name: スキルカード追加発動
  swapName: スキルカード追加発動
  produceDescriptionId: Label_ExamCardSearchEffectPlayCountBuff_Produce
  examProduceDescriptionId: Label_ExamCardSearchEffectPlayCountBuff
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamLessonValueMultiple
  name: パラメータ上昇量増加
  swapName: スコア上昇量増加
  produceDescriptionId: Label_ExamLessonValueMultiple
  examProduceDescriptionId: Label_ExamLessonValueMultiple
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamCardPlayAggressive
  name: やる気
  swapName: やる気
  produceDescriptionId: Label_ExamCardPlayAggressive_Produce
  examProduceDescriptionId: Label_ExamCardPlayAggressive_Exam
  mainBuffMinThresholds:
  - 5
  - 10
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamConcentration
  name: 強気
  swapName: 強気
  produceDescriptionId: Label_ExamConcentration_Produce
  examProduceDescriptionId: Label_ExamConcentration_Exam
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamPreservation
  name: 温存
  swapName: 温存
  produceDescriptionId: Label_ExamPreservation_Produce
  examProduceDescriptionId: Label_ExamPreservation_Exam
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamFullPower
  name: 全力
  swapName: 全力
  produceDescriptionId: Label_ExamFullPower
  examProduceDescriptionId: Label_ExamFullPower
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamStanceReset
  name: 指針解除
  swapName: 指針解除
  produceDescriptionId: Label_ExamStanceReset
  examProduceDescriptionId: Label_ExamStanceReset
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamFullPowerPoint
  name: 全力値
  swapName: 全力値
  produceDescriptionId: Label_ExamFullPowerPoint
  examProduceDescriptionId: Label_ExamFullPowerPoint
  mainBuffMinThresholds:
  - 5
  - 10
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamFullPowerPointReduce
  name: 全力値減少
  swapName: 全力値減少
  produceDescriptionId: Label_ExamFullPowerPointReduce
  examProduceDescriptionId: Label_ExamFullPowerPointReduce
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamSearchPlayCardStaminaConsumptionChange
  name: 消費体力変化
  swapName: 消費体力変化
  produceDescriptionId: Label_ExamSearchPlayCardStaminaConsumptionChange
  examProduceDescriptionId: Label_ExamSearchPlayCardStaminaConsumptionChange
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamUplifting
  name: 高揚
  swapName: 高揚
  produceDescriptionId: Label_ExamUplifting_Produce
  examProduceDescriptionId: Label_ExamUplifting_Exam
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamExtraTurn
  name: ターン追加
  swapName: ターン追加
  produceDescriptionId: Label_ExamExtraTurn
  examProduceDescriptionId: Label_ExamExtraTurn
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamAntiDebuff
  name: 低下状態無効
  swapName: 低下状態無効
  produceDescriptionId: Label_ExamAntiDebuff
  examProduceDescriptionId: Label_ExamAntiDebuff
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamStaminaConsumptionAdd
  name: 消費体力増加
  swapName: 消費体力増加
  produceDescriptionId: Label_ExamStaminaConsumptionAdd
  examProduceDescriptionId: Label_ExamStaminaConsumptionAdd
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamBlockAddDown
  name: 不安
  swapName: 不安
  produceDescriptionId: Label_ExamBlockAddDown
  examProduceDescriptionId: Label_ExamBlockAddDown
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamBlockAddDownRestriction
  name: 不安無効
  swapName: 不安無効
  produceDescriptionId: Label_ExamBlockAddDownRestriction
  examProduceDescriptionId: Label_ExamBlockAddDownRestriction
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamStaminaRecoverAdd
  name: 体力回復効果増加
  swapName: 体力回復効果増加
  produceDescriptionId: Label_ExamStaminaRecoverAdd
  examProduceDescriptionId: Label_ExamStaminaRecoverAdd
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamStaminaReduceChange
  name: 体力消費軽減
  swapName: 体力消費軽減
  produceDescriptionId: Label_ExamStaminaReduceChange
  examProduceDescriptionId: Label_ExamStaminaReduceChange
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamPanic
  name: 気まぐれ
  swapName: 気まぐれ
  produceDescriptionId: Label_ExamPanic
  examProduceDescriptionId: Label_ExamPanic
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamLessonChangeSpecifyLessThan
  name: パラメータ上昇値変更
  swapName: スコア上昇値変更
  produceDescriptionId: Label_ExamLessonChangeSpecifyLessThan
  examProduceDescriptionId: Label_ExamLessonChangeSpecifyLessThan
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamHandHold
  name: 手札持ち越し
  swapName: 手札持ち越し
  produceDescriptionId: Label_ExamHandHold
  examProduceDescriptionId: Label_ExamHandHold
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamStaminaConsumptionAddFix
  name: 消費体力追加
  swapName: 消費体力追加
  produceDescriptionId: Label_ExamStaminaConsumptionAddFix
  examProduceDescriptionId: Label_ExamStaminaConsumptionAddFix
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamStaminaConsumptionAddDown
  name: 消費体力増加効果減少
  swapName: 消費体力増加効果減少
  produceDescriptionId: Label_ExamStaminaConsumptionAddDown
  examProduceDescriptionId: Label_ExamStaminaConsumptionAddDown
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamStaminaRecoverRestriction
  name: 体力回復無効
  swapName: 体力回復無効
  produceDescriptionId: Label_ExamStaminaRecoverRestriction
  examProduceDescriptionId: Label_ExamStaminaRecoverRestriction
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamStaminaConsumptionDownAdd
  name: 消費体力減少効果増加
  swapName: 消費体力減少効果増加
  produceDescriptionId: Label_ExamStaminaConsumptionDownAdd
  examProduceDescriptionId: Label_ExamStaminaConsumptionDownAdd
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamGetCardUpgrade
  name: 生成強化
  swapName: 生成強化
  produceDescriptionId: Label_ExamGetCardUpgrade
  examProduceDescriptionId: Label_ExamGetCardUpgrade
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamStaminaConsumptionDownFix
  name: 消費体力削減
  swapName: 消費体力削減
  produceDescriptionId: Label_ExamStaminaConsumptionDownFix
  examProduceDescriptionId: Label_ExamStaminaConsumptionDownFix
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamHandGraveCountCardDraw
  name: 手札を入れ替える
  swapName: 手札を入れ替える
  produceDescriptionId: Label_ExamHandGraveCountCardDraw
  examProduceDescriptionId: Label_ExamHandGraveCountCardDraw
  mainBuffMinThresholds: []
  noIcon: false
  noReference: true
- type: ProduceExamEffectType_ExamEffectTimer
  name: 発動予約
  swapName: 発動予約
  produceDescriptionId: Label_ExamEffectTimer
  examProduceDescriptionId: Label_ExamEffectTimer
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamGimmickLessonDebuff
  name: 緊張
  swapName: 緊張
  produceDescriptionId: Label_ExamGimmickLessonDebuff_Produce
  examProduceDescriptionId: Label_ExamGimmickLessonDebuff_Exam
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamGimmickParameterDebuff
  name: 不調
  swapName: 不調
  produceDescriptionId: Label_ExamGimmickParameterDebuff
  examProduceDescriptionId: Label_ExamGimmickParameterDebuff
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamGimmickSleepy
  name: 弱気
  swapName: 弱気
  produceDescriptionId: Label_ExamGimmickSleepy_Produce
  examProduceDescriptionId: Label_ExamGimmickSleepy_Exam
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamGimmickEnthusiastic
  name: 熱意
  swapName: 熱意
  produceDescriptionId: Label_ExamGimmickEnthusiastic_Produce
  examProduceDescriptionId: Label_ExamGimmickEnthusiastic_Exam
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamGimmickPlayCardLimit
  name: 使用不可
  swapName: 使用不可
  produceDescriptionId: Label_ExamGimmickPlayCardLimit
  examProduceDescriptionId: Label_ExamGimmickPlayCardLimit
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamGimmickSlump
  name: スランプ
  swapName: スランプ
  produceDescriptionId: Label_ExamGimmickSlump
  examProduceDescriptionId: Label_ExamGimmickSlump
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamGimmickStartTurnCardDrawDown
  name: 手札減少
  swapName: 手札減少
  produceDescriptionId: Label_ExamGimmickStartTurnCardDrawDown_Produce
  examProduceDescriptionId: Label_ExamGimmickStartTurnCardDrawDown_Exam
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamBlockFix
  name: 固定元気
  swapName: 固定元気
  produceDescriptionId: Label_ExamBlockFix
  examProduceDescriptionId: Label_ExamBlockFix
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamLessonChangeSpecifyMoreThan
  name: うわの空
  swapName: うわの空
  produceDescriptionId: Label_ExamLessonChangeSpecifyMoreThan
  examProduceDescriptionId: Label_ExamLessonChangeSpecifyMoreThan
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamParameterBuffMultiplePerTurn
  name: 絶好調
  swapName: 絶好調
  produceDescriptionId: Label_ExamParameterBuffMultiplePerTurn
  examProduceDescriptionId: Label_ExamParameterBuffMultiplePerTurn
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_StanceLock
  name: 指針固定
  swapName: 指針固定
  produceDescriptionId: Label_StanceLock
  examProduceDescriptionId: Label_StanceLock
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamDebuffRecover
  name: 低下状態回復
  swapName: 低下状態回復
  produceDescriptionId: Label_ExamDebuffRecover
  examProduceDescriptionId: Label_ExamDebuffRecover
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamReviewReduce
  name: 好印象減少
  swapName: 好印象減少
  produceDescriptionId: Label_ExamReviewReduce
  examProduceDescriptionId: Label_ExamReviewReduce
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamAggressiveReduce
  name: やる気減少
  swapName: やる気減少
  produceDescriptionId: Label_ExamAggressiveReduce
  examProduceDescriptionId: Label_ExamAggressiveReduce
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamLessonBuffReduce
  name: 集中減少
  swapName: 集中減少
  produceDescriptionId: Label_ExamLessonBuffReduce
  examProduceDescriptionId: Label_ExamLessonBuffReduce
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamParameterBuffReduce
  name: 好調減少
  swapName: 好調減少
  produceDescriptionId: Label_ExamParameterBuffReduce
  examProduceDescriptionId: Label_ExamParameterBuffReduce
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamLessonValueMultipleDown
  name: パラメータ上昇量減少
  swapName: スコア上昇量減少
  produceDescriptionId: Label_ExamLessonValueMultipleDown
  examProduceDescriptionId: Label_ExamLessonValueMultipleDown
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false
- type: ProduceExamEffectType_ExamAddGrowEffect
  name: 成長効果
  swapName: 成長効果
  produceDescriptionId: Label_ExamAddGrowEffect
  examProduceDescriptionId: Label_ExamAddGrowEffect
  mainBuffMinThresholds: []
  noIcon: false
  noReference: false