- id: Swap_Convert_001
  swapType: ProduceDescriptionSwapType_Lesson
  text: レッスン
- id: Swap_Convert_001
  swapType: ProduceDescriptionSwapType_Audition
  text: ターン
- id: Swap_Convert_002
  swapType: ProduceDescriptionSwapType_Lesson
  text: レッスン
- id: Swap_Convert_002
  swapType: ProduceDescriptionSwapType_Audition
  text: 試験・ステージ
- id: Swap_Convert_ConditionThreshold
  swapType: ProduceDescriptionSwapType_Lesson
  text: レッスンCLEARの
- id: Swap_Convert_ConditionThreshold
  swapType: ProduceDescriptionSwapType_Audition
  text: スコアが
- id: Swap_Convert_ConditionThreshold_NotClear
  swapType: ProduceDescriptionSwapType_Lesson
  text: レッスン未CLEAR
- id: Swap_Convert_ConditionThreshold_NotClear
  swapType: ProduceDescriptionSwapType_Audition
  text: スコアが999以下
- id: Swap_Convert_ConditionThreshold_Value_100
  swapType: ProduceDescriptionSwapType_Lesson
  text: 10%
- id: Swap_Convert_ConditionThreshold_Value_100
  swapType: ProduceDescriptionSwapType_Audition
  text: "100"
- id: Swap_Convert_ConditionThreshold_Value_1000
  swapType: ProduceDescriptionSwapType_Lesson
  text: 100%
- id: Swap_Convert_ConditionThreshold_Value_1000
  swapType: ProduceDescriptionSwapType_Audition
  text: "1000"
- id: Swap_Convert_ConditionThreshold_Value_300
  swapType: ProduceDescriptionSwapType_Lesson
  text: 30%
- id: Swap_Convert_ConditionThreshold_Value_300
  swapType: ProduceDescriptionSwapType_Audition
  text: "300"
- id: Swap_Convert_ConditionThreshold_Value_500
  swapType: ProduceDescriptionSwapType_Lesson
  text: 50%
- id: Swap_Convert_ConditionThreshold_Value_500
  swapType: ProduceDescriptionSwapType_Audition
  text: "500"
- id: Swap_Convert_StepLessonType_DanceLesson
  swapType: ProduceDescriptionSwapType_Lesson
  text: 【ダンスレッスン・ダンスターンのみ】
- id: Swap_Convert_StepLessonType_DanceLesson
  swapType: ProduceDescriptionSwapType_Audition
  text: ダンスターンなら、
- id: Swap_Convert_StepLessonType_SpLesson
  swapType: ProduceDescriptionSwapType_Lesson
  text: 【SPレッスンのみ】
- id: Swap_Convert_StepLessonType_SpLesson
  swapType: ProduceDescriptionSwapType_Audition
  text: 【SPレッスンのみ】
- id: Swap_Convert_StepLessonType_VisualLesson
  swapType: ProduceDescriptionSwapType_Lesson
  text: 【ビジュアルレッスン・ビジュアルターンのみ】
- id: Swap_Convert_StepLessonType_VisualLesson
  swapType: ProduceDescriptionSwapType_Audition
  text: ビジュアルターンなら、
- id: Swap_Convert_StepLessonType_VocalLesson
  swapType: ProduceDescriptionSwapType_Lesson
  text: 【ボーカルレッスン・ボーカルターンのみ】
- id: Swap_Convert_StepLessonType_VocalLesson
  swapType: ProduceDescriptionSwapType_Audition
  text: ボーカルターンなら、
- id: Swap_Label_Audition
  swapType: ProduceDescriptionSwapType_Lesson
  text: 試験・オーディション
- id: Swap_Label_Audition
  swapType: ProduceDescriptionSwapType_Audition
  text: 試験・オーディション
- id: Swap_Label_ExamCardUpgrade
  swapType: ProduceDescriptionSwapType_Lesson
  text: レッスン中強化
- id: Swap_Label_ExamCardUpgrade
  swapType: ProduceDescriptionSwapType_Audition
  text: 試験・ステージ中強化
- id: Swap_Label_ExamGrowEffectLessonAddAdditive
  swapType: ProduceDescriptionSwapType_Lesson
  text: パラメータ上昇値増加量増加
- id: Swap_Label_ExamGrowEffectLessonAddAdditive
  swapType: ProduceDescriptionSwapType_Audition
  text: スコア上昇値増加量増加
- id: Swap_Label_ExamLesson
  swapType: ProduceDescriptionSwapType_Lesson
  text: パラメータ
- id: Swap_Label_ExamLesson
  swapType: ProduceDescriptionSwapType_Audition
  text: スコア
- id: Swap_Label_ExamLessonChangeSpecifyLessThan
  swapType: ProduceDescriptionSwapType_Lesson
  text: パラメータ上昇値変更
- id: Swap_Label_ExamLessonChangeSpecifyLessThan
  swapType: ProduceDescriptionSwapType_Audition
  text: スコア上昇値変更
- id: Swap_Label_ExamLessonFix
  swapType: ProduceDescriptionSwapType_Lesson
  text: 固定パラメータ
- id: Swap_Label_ExamLessonFix
  swapType: ProduceDescriptionSwapType_Audition
  text: 固定スコア
- id: Swap_Label_ExamLessonValueMultiple
  swapType: ProduceDescriptionSwapType_Lesson
  text: パラメータ上昇量増加
- id: Swap_Label_ExamLessonValueMultiple
  swapType: ProduceDescriptionSwapType_Audition
  text: スコア上昇量増加
- id: Swap_Label_ExamLessonValueMultipleDown
  swapType: ProduceDescriptionSwapType_Lesson
  text: パラメータ上昇量減少
- id: Swap_Label_ExamLessonValueMultipleDown
  swapType: ProduceDescriptionSwapType_Audition
  text: スコア上昇量減少
- id: Swap_Label_ExamStaminaDamage
  swapType: ProduceDescriptionSwapType_Lesson
  text: 体力減少
- id: Swap_Label_ExamStaminaDamage
  swapType: ProduceDescriptionSwapType_Audition
  text: 体力減少
- id: Swap_Label_ExamStaminaRecoverFix
  swapType: ProduceDescriptionSwapType_Lesson
  text: 体力回復
- id: Swap_Label_ExamStaminaRecoverFix
  swapType: ProduceDescriptionSwapType_Audition
  text: 体力回復
- id: Swap_Label_LessonAdd
  swapType: ProduceDescriptionSwapType_Lesson
  text: パラメータ値増加
- id: Swap_Label_LessonAdd
  swapType: ProduceDescriptionSwapType_Audition
  text: スコア値増加
- id: Swap_Label_LessonCountAdd
  swapType: ProduceDescriptionSwapType_Lesson
  text: パラメータ上昇回数増加
- id: Swap_Label_LessonCountAdd
  swapType: ProduceDescriptionSwapType_Audition
  text: スコア上昇回数増加
- id: Swap_Label_LessonCountReduce
  swapType: ProduceDescriptionSwapType_Lesson
  text: パラメータ上昇回数減少
- id: Swap_Label_LessonCountReduce
  swapType: ProduceDescriptionSwapType_Audition
  text: スコア上昇回数減少
- id: Swap_Label_LessonReduce
  swapType: ProduceDescriptionSwapType_Lesson
  text: パラメータ値減少
- id: Swap_Label_LessonReduce
  swapType: ProduceDescriptionSwapType_Audition
  text: スコア値減少
- id: Swap_Label_ProduceCardMovePositionType_Lost
  swapType: ProduceDescriptionSwapType_Lesson
  text: レッスン中1回
- id: Swap_Label_ProduceCardMovePositionType_Lost
  swapType: ProduceDescriptionSwapType_Audition
  text: 試験・ステージ中1回
- id: Swap_Label_ProduceCardPositionType_DeckFirst
  swapType: ProduceDescriptionSwapType_Lesson
  text: 山札の上
- id: Swap_Label_ProduceCardPositionType_DeckFirst
  swapType: ProduceDescriptionSwapType_Audition
  text: 山札の上
- id: Swap_Label_ProduceCardPositionType_DeckLast
  swapType: ProduceDescriptionSwapType_Lesson
  text: 山札の下
- id: Swap_Label_ProduceCardPositionType_DeckLast
  swapType: ProduceDescriptionSwapType_Audition
  text: 山札の下
- id: Swap_Label_ProduceCardPositionType_DeckRandom
  swapType: ProduceDescriptionSwapType_Lesson
  text: 山札のランダムな位置
- id: Swap_Label_ProduceCardPositionType_DeckRandom
  swapType: ProduceDescriptionSwapType_Audition
  text: 山札のランダムな位置
- id: Swap_Label_ProduceCardPositionType_Grave
  swapType: ProduceDescriptionSwapType_Lesson
  text: 捨札
- id: Swap_Label_ProduceCardPositionType_Grave
  swapType: ProduceDescriptionSwapType_Audition
  text: 捨札
- id: Swap_Label_ProduceCardPositionType_Hand
  swapType: ProduceDescriptionSwapType_Lesson
  text: 手札
- id: Swap_Label_ProduceCardPositionType_Hand
  swapType: ProduceDescriptionSwapType_Audition
  text: 手札
- id: Swap_Label_ProduceCardPositionType_Lost
  swapType: ProduceDescriptionSwapType_Lesson
  text: 除外
- id: Swap_Label_ProduceCardPositionType_Lost
  swapType: ProduceDescriptionSwapType_Audition
  text: 除外