- id: p_step_audition_difficulty-amao
  produceId: produce-001
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 100
  baseScore: 600
  forceEndScore: 900
  produceExamBattleNpcGroupId: p_npc_group-amao-produce-001-1
  produceExamBattleConfigId: p_exam_battle_config-vovi-04-produce-001-1-1
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-amao
  produceId: produce-001
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 200
  baseScore: 2500
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-amao-produce-001-2
  produceExamBattleConfigId: p_exam_battle_config-vovi-04-produce-001-2-1
  produceExamGimmickEffectGroupId: p_e_gim-exam_parameter_buff-2-produce-001-produce-audition-final
- id: p_step_audition_difficulty-amao
  produceId: produce-002
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 150
  baseScore: 1150
  forceEndScore: 1700
  produceExamBattleNpcGroupId: p_npc_group-amao-produce-002-1
  produceExamBattleConfigId: p_exam_battle_config-vovi-04-produce-002-1-1
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-amao
  produceId: produce-002
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 450
  baseScore: 7100
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-amao-produce-002-2
  produceExamBattleConfigId: p_exam_battle_config-vovi-04-produce-002-2-1
  produceExamGimmickEffectGroupId: p_e_gim-exam_parameter_buff-2-produce-002-produce-audition-final
- id: p_step_audition_difficulty-fktn
  produceId: produce-001
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 100
  baseScore: 600
  forceEndScore: 900
  produceExamBattleNpcGroupId: p_npc_group-fktn-produce-001-1
  produceExamBattleConfigId: p_exam_battle_config-davi-04-produce-001-1-2
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-fktn
  produceId: produce-001
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 200
  baseScore: 2500
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-fktn-produce-001-2
  produceExamBattleConfigId: p_exam_battle_config-davi-04-produce-001-2-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_review-1-produce-001-produce-audition-final
- id: p_step_audition_difficulty-fktn
  produceId: produce-002
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 150
  baseScore: 1150
  forceEndScore: 1700
  produceExamBattleNpcGroupId: p_npc_group-fktn-produce-002-1
  produceExamBattleConfigId: p_exam_battle_config-davi-04-produce-002-1-2
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-fktn
  produceId: produce-002
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 450
  baseScore: 7100
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-fktn-produce-002-2
  produceExamBattleConfigId: p_exam_battle_config-davi-04-produce-002-2-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_review-1-produce-002-produce-audition-final
- id: p_step_audition_difficulty-hrnm
  produceId: produce-001
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 100
  baseScore: 600
  forceEndScore: 900
  produceExamBattleNpcGroupId: p_npc_group-hrnm-produce-001-1
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-001-1-1
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-hrnm
  produceId: produce-001
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 200
  baseScore: 2450
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-hrnm-produce-001-2
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-001-2-1
  produceExamGimmickEffectGroupId: p_e_gim-exam_lesson_buff-2-produce-001-produce-audition-final
- id: p_step_audition_difficulty-hrnm
  produceId: produce-002
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 150
  baseScore: 1150
  forceEndScore: 1700
  produceExamBattleNpcGroupId: p_npc_group-hrnm-produce-002-1
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-002-1-1
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-hrnm
  produceId: produce-002
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 400
  baseScore: 6950
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-hrnm-produce-002-2
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-002-2-1
  produceExamGimmickEffectGroupId: p_e_gim-exam_lesson_buff-2-produce-002-produce-audition-final
- id: p_step_audition_difficulty-hski
  produceId: produce-001
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 100
  baseScore: 600
  forceEndScore: 900
  produceExamBattleNpcGroupId: p_npc_group-hski-produce-001-1
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-001-1-1
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-hski
  produceId: produce-001
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 200
  baseScore: 2450
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-hski-produce-001-2
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-001-2-1
  produceExamGimmickEffectGroupId: p_e_gim-exam_parameter_buff-1-produce-001-produce-audition-final
- id: p_step_audition_difficulty-hski
  produceId: produce-002
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 150
  baseScore: 1150
  forceEndScore: 1700
  produceExamBattleNpcGroupId: p_npc_group-hski-produce-002-1
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-002-1-1
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-hski
  produceId: produce-002
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 400
  baseScore: 6950
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-hski-produce-002-2
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-002-2-1
  produceExamGimmickEffectGroupId: p_e_gim-exam_parameter_buff-1-produce-002-produce-audition-final
- id: p_step_audition_difficulty-kcna
  produceId: produce-001
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 100
  baseScore: 600
  forceEndScore: 900
  produceExamBattleNpcGroupId: p_npc_group-kcna-produce-001-1
  produceExamBattleConfigId: p_exam_battle_config-davi-01-produce-001-1-2
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-kcna
  produceId: produce-001
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 250
  baseScore: 2550
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-kcna-produce-001-2
  produceExamBattleConfigId: p_exam_battle_config-davi-01-produce-001-2-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_card_play_aggressive-1-produce-001-produce-audition-final
- id: p_step_audition_difficulty-kcna
  produceId: produce-002
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 150
  baseScore: 1150
  forceEndScore: 1700
  produceExamBattleNpcGroupId: p_npc_group-kcna-produce-002-1
  produceExamBattleConfigId: p_exam_battle_config-davi-01-produce-002-1-2
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-kcna
  produceId: produce-002
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 500
  baseScore: 7300
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-kcna-produce-002-2
  produceExamBattleConfigId: p_exam_battle_config-davi-01-produce-002-2-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_card_play_aggressive-1-produce-002-produce-audition-final
- id: p_step_audition_difficulty-kllj
  produceId: produce-001
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 100
  baseScore: 600
  forceEndScore: 900
  produceExamBattleNpcGroupId: p_npc_group-kllj-produce-001-1
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-001-1-2
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-kllj
  produceId: produce-001
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 200
  baseScore: 2450
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-kllj-produce-001-2
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-001-2-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_review-2-produce-001-produce-audition-final
- id: p_step_audition_difficulty-kllj
  produceId: produce-002
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 150
  baseScore: 1150
  forceEndScore: 1700
  produceExamBattleNpcGroupId: p_npc_group-kllj-produce-002-1
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-002-1-2
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-kllj
  produceId: produce-002
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 400
  baseScore: 6950
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-kllj-produce-002-2
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-002-2-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_review-2-produce-002-produce-audition-final
- id: p_step_audition_difficulty-shro
  produceId: produce-001
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 100
  baseScore: 600
  forceEndScore: 900
  produceExamBattleNpcGroupId: p_npc_group-shro-produce-001-1
  produceExamBattleConfigId: p_exam_battle_config-voda-03-produce-001-1-2
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-shro
  produceId: produce-001
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 200
  baseScore: 2450
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-shro-produce-001-2
  produceExamBattleConfigId: p_exam_battle_config-voda-03-produce-001-2-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_card_play_aggressive-2-produce-001-produce-audition-final
- id: p_step_audition_difficulty-shro
  produceId: produce-002
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 150
  baseScore: 1150
  forceEndScore: 1700
  produceExamBattleNpcGroupId: p_npc_group-shro-produce-002-1
  produceExamBattleConfigId: p_exam_battle_config-voda-03-produce-002-1-2
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-shro
  produceId: produce-002
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 400
  baseScore: 6950
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-shro-produce-002-2
  produceExamBattleConfigId: p_exam_battle_config-voda-03-produce-002-2-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_card_play_aggressive-2-produce-002-produce-audition-final
- id: p_step_audition_difficulty-ssmk
  produceId: produce-001
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 100
  baseScore: 600
  forceEndScore: 900
  produceExamBattleNpcGroupId: p_npc_group-ssmk-produce-001-1
  produceExamBattleConfigId: p_exam_battle_config-davi-02-produce-001-1-1
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-ssmk
  produceId: produce-001
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 300
  baseScore: 2650
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-ssmk-produce-001-2
  produceExamBattleConfigId: p_exam_battle_config-davi-02-produce-001-2-1
  produceExamGimmickEffectGroupId: p_e_gim-exam_lesson_buff-3-produce-001-produce-audition-final
- id: p_step_audition_difficulty-ssmk
  produceId: produce-002
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 200
  baseScore: 1200
  forceEndScore: 1800
  produceExamBattleNpcGroupId: p_npc_group-ssmk-produce-002-1
  produceExamBattleConfigId: p_exam_battle_config-davi-02-produce-002-1-1
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-ssmk
  produceId: produce-002
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 600
  baseScore: 7650
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-ssmk-produce-002-2
  produceExamBattleConfigId: p_exam_battle_config-davi-02-produce-002-2-1
  produceExamGimmickEffectGroupId: p_e_gim-exam_lesson_buff-3-produce-002-produce-audition-final
- id: p_step_audition_difficulty-ttmr
  produceId: produce-001
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 100
  baseScore: 600
  forceEndScore: 900
  produceExamBattleNpcGroupId: p_npc_group-ttmr-produce-001-1
  produceExamBattleConfigId: p_exam_battle_config-voda-01-produce-001-1-1
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-ttmr
  produceId: produce-001
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 250
  baseScore: 2550
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-ttmr-produce-001-2
  produceExamBattleConfigId: p_exam_battle_config-voda-01-produce-001-2-1
  produceExamGimmickEffectGroupId: p_e_gim-exam_lesson_buff-2-produce-001-produce-audition-final
- id: p_step_audition_difficulty-ttmr
  produceId: produce-002
  stepType: ProduceStepType_AuditionMid1
  number: 1
  rankThreshold: 3
  parameterBaseLine: 150
  baseScore: 1150
  forceEndScore: 1700
  produceExamBattleNpcGroupId: p_npc_group-ttmr-produce-002-1
  produceExamBattleConfigId: p_exam_battle_config-voda-01-produce-002-1-1
  produceExamGimmickEffectGroupId: ""
- id: p_step_audition_difficulty-ttmr
  produceId: produce-002
  stepType: ProduceStepType_AuditionFinal
  number: 1
  rankThreshold: 3
  parameterBaseLine: 500
  baseScore: 7300
  forceEndScore: 0
  produceExamBattleNpcGroupId: p_npc_group-ttmr-produce-002-2
  produceExamBattleConfigId: p_exam_battle_config-voda-01-produce-002-2-1
  produceExamGimmickEffectGroupId: p_e_gim-exam_lesson_buff-2-produce-002-produce-audition-final