- id: producer_ranking_tower-000
  towerId: tower_001-amao
  layerNumbers:
  - 24
- id: producer_ranking_tower-000
  towerId: tower_001-fktn
  layerNumbers:
  - 24
- id: producer_ranking_tower-000
  towerId: tower_001-hmsz
  layerNumbers:
  - 24
- id: producer_ranking_tower-000
  towerId: tower_001-hrnm
  layerNumbers:
  - 24
- id: producer_ranking_tower-000
  towerId: tower_001-hski
  layerNumbers:
  - 24
- id: producer_ranking_tower-000
  towerId: tower_001-hume
  layerNumbers:
  - 24
- id: producer_ranking_tower-000
  towerId: tower_001-jsna
  layerNumbers:
  - 24
- id: producer_ranking_tower-000
  towerId: tower_001-kcna
  layerNumbers:
  - 24
- id: producer_ranking_tower-000
  towerId: tower_001-kllj
  layerNumbers:
  - 24
- id: producer_ranking_tower-000
  towerId: tower_001-shro
  layerNumbers:
  - 24
- id: producer_ranking_tower-000
  towerId: tower_001-ssmk
  layerNumbers:
  - 24
- id: producer_ranking_tower-000
  towerId: tower_001-ttmr
  layerNumbers:
  - 24
- id: producer_ranking_tower-001
  towerId: tower_001-amao
  layerNumbers:
  - 22
- id: producer_ranking_tower-001
  towerId: tower_001-atbm
  layerNumbers:
  - 22
- id: producer_ranking_tower-001
  towerId: tower_001-fktn
  layerNumbers:
  - 22
- id: producer_ranking_tower-001
  towerId: tower_001-hmsz
  layerNumbers:
  - 22
- id: producer_ranking_tower-001
  towerId: tower_001-hrnm
  layerNumbers:
  - 22
- id: producer_ranking_tower-001
  towerId: tower_001-hski
  layerNumbers:
  - 22
- id: producer_ranking_tower-001
  towerId: tower_001-hume
  layerNumbers:
  - 22
- id: producer_ranking_tower-001
  towerId: tower_001-jsna
  layerNumbers:
  - 22
- id: producer_ranking_tower-001
  towerId: tower_001-kcna
  layerNumbers:
  - 22
- id: producer_ranking_tower-001
  towerId: tower_001-kllj
  layerNumbers:
  - 22
- id: producer_ranking_tower-001
  towerId: tower_001-shro
  layerNumbers:
  - 22
- id: producer_ranking_tower-001
  towerId: tower_001-ssmk
  layerNumbers:
  - 22
- id: producer_ranking_tower-001
  towerId: tower_001-ttmr
  layerNumbers:
  - 22