- produceType: ProduceType_FirstStar
  produceSplitType: ProduceSplitType_Unknown
  name: 初専用　
  template: "{Label_ProduceType_FirstStar}"
- produceType: ProduceType_NextIdolAudition
  produceSplitType: ProduceSplitType_Unknown
  name: N.I.A専用　
  template: "{Label_ProduceType_NextIdolAudition}"
- produceType: ProduceType_HatsuboshiIdolFestival
  produceSplitType: ProduceSplitType_Unknown
  name: H.I.F専用　
  template: "{Label_ProduceType_HatsuboshiIdolFestival}"
- produceType: ProduceType_HatsuboshiIdolFestival
  produceSplitType: ProduceSplitType_Selection
  name: H.I.F選抜試験専用　
  template: "{Label_ProduceType_HatsuboshiIdolFestival_Selection}"
- produceType: ProduceType_HatsuboshiIdolFestival
  produceSplitType: ProduceSplitType_Final
  name: H.I.F本戦専用　
  template: "{Label_ProduceType_HatsuboshiIdolFestival_Final}"