- id: produce_group-001
  name: 定期公演『初』
  type: ProduceType_FirstStar
  produceIds:
  - produce-001
  - produce-002
  - produce-003
  - produce-006
  assetId: produce-group-1
  viewConditionSetId: ""
  unlockConditionSetId: ""
  failedProduceMemoryAssetId: img_general_memory_all-produce-failure-001
  description: |-
    定期公演『初』──それは、初星学園アイドル科の
    成績上位者のみ立つことができるステージ
    自分を磨き、今、彼女たちは輝きはじめる──
  isForceLiveCommon: false
  disableForceLiveCommonEndingLiveType: ProduceLiveType_Unknown
  limitGrade: ResultGrade_Ssss
  order: 1
- id: produce_group-002
  name: NEXT IDOL AUDITION
  type: ProduceType_NextIdolAudition
  produceIds:
  - produce-004
  - produce-005
  assetId: produce-group-2
  viewConditionSetId: ""
  unlockConditionSetId: cd-nia_produce-unlock_open
  failedProduceMemoryAssetId: img_general_memory_all-produce-failure-002
  description: |-
    『NEXT IDOL AUDITION』──通称『N.I.A』
    次代を担うアイドルの頂点を決める戦いが開幕！
    ファンを集めて、今、栄光のステージへ──
  isForceLiveCommon: true
  disableForceLiveCommonEndingLiveType: ProduceLiveType_TrueEnd
  limitGrade: ResultGrade_SssPlus
  order: 2