- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_BeforeFinalAuditionRefresh
  produceSplitTypes: ProduceSplitType_Selection
  targetCharacterId: ""
  title: 第3回『選抜試験』前
  assetId: adv_produce-refresh_003_selection_03
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_BeforeFinalAuditionRefresh
  produceSplitTypes: ProduceSplitType_Final
  targetCharacterId: ""
  title: 『本戦』ラウンド2前
  assetId: adv_produce-refresh_003_final_02
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_BeforeMid1AuditionRefresh
  produceSplitTypes: ProduceSplitType_Selection
  targetCharacterId: ""
  title: 第1回『選抜試験』前
  assetId: adv_produce-refresh_003_selection_01
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_BeforeMid1AuditionRefresh
  produceSplitTypes: ProduceSplitType_Final
  targetCharacterId: ""
  title: 決戦の舞台へ！
  assetId: adv_produce-refresh_003_final_01
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_BeforeMid2AuditionRefresh
  produceSplitTypes: ProduceSplitType_Selection
  targetCharacterId: ""
  title: 第2回『選抜試験』前
  assetId: adv_produce-refresh_003_selection_02
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_Opening
  produceSplitTypes: ProduceSplitType_Selection
  targetCharacterId: ""
  title: H.I.F選抜試験
  assetId: adv_pstory_003_cmmn_world-explanation-selection
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_Opening
  produceSplitTypes: ProduceSplitType_Final
  targetCharacterId: ""
  title: H.I.F本戦
  assetId: adv_pstory_003_cmmn_world-explanation-final
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultTrueEnd
  produceSplitTypes: ProduceSplitType_Selection
  targetCharacterId: ""
  title: 『選抜試験』の結果は……
  assetId: adv_presult_003_selection-true
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultTrueEnd
  produceSplitTypes: ProduceSplitType_Final
  targetCharacterId: ""
  title: 『H.I.F』本戦の結果は……
  assetId: adv_presult_003_final-true
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultA
  produceSplitTypes: ProduceSplitType_Selection
  targetCharacterId: ""
  title: 『選抜試験』の結果は……
  assetId: adv_presult_003_selection-true
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultA
  produceSplitTypes: ProduceSplitType_Final
  targetCharacterId: ""
  title: 『H.I.F』本戦の結果は……
  assetId: adv_pstory_003_cmmn_final-normal-03
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultB
  produceSplitTypes: ProduceSplitType_Selection
  targetCharacterId: ""
  title: 『選抜試験』の結果は……
  assetId: adv_presult_003_selection-true
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultB
  produceSplitTypes: ProduceSplitType_Final
  targetCharacterId: ""
  title: 『H.I.F』本戦の結果は……
  assetId: adv_pstory_003_cmmn_final-normal-03
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultC
  produceSplitTypes: ProduceSplitType_Selection
  targetCharacterId: ""
  title: 『選抜試験』の結果は……
  assetId: adv_presult_003_selection-true
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultC
  produceSplitTypes: ProduceSplitType_Final
  targetCharacterId: ""
  title: 『H.I.F』本戦の結果は……
  assetId: adv_pstory_003_cmmn_final-normal-03
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultFailedFinal
  produceSplitTypes: ProduceSplitType_Selection
  targetCharacterId: ""
  title: 『選抜試験』の結果は……
  assetId: adv_presult_003_selection-failure
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultFailedFinal
  produceSplitTypes: ProduceSplitType_Final
  targetCharacterId: ""
  title: 『H.I.F』本戦の結果は……
  assetId: adv_presult_003_final-failure
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultFailedMid1
  produceSplitTypes: ProduceSplitType_Selection
  targetCharacterId: ""
  title: 『選抜試験』の結果は……
  assetId: adv_presult_003_selection-failure
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultFailedMid1
  produceSplitTypes: ProduceSplitType_Final
  targetCharacterId: ""
  title: 『H.I.F』本戦の結果は……
  assetId: adv_presult_003_final-failure
- produceType: ProduceType_HatsuboshiIdolFestival
  type: ProduceAdvType_ProduceResultFailedMid2
  produceSplitTypes: ProduceSplitType_Selection
  targetCharacterId: ""
  title: 『選抜試験』の結果は……
  assetId: adv_presult_003_selection-failure