- id: reversi
  produceGroupId: produce_group-003
  targetCharacterId: kllj
  unitCharacterId: ssmk
  name: REVERSI
  liveCostumeId: ""
  liveCostumeHeadId: ""
- id: reversi
  produceGroupId: produce_group-003
  targetCharacterId: ssmk
  unitCharacterId: kllj
  name: REVERSI
  liveCostumeId: ""
  liveCostumeHeadId: ""