- characterId: amao
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: amao
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid2
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: amao
  produceId: produce-007
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: amao
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-01
- characterId: amao
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09
- characterId: hmsz
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hmsz
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid2
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hmsz
  produceId: produce-007
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hmsz
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-01
- characterId: hmsz
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09
- characterId: hrnm
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hrnm
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid2
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hrnm
  produceId: produce-007
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: hrnm
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-01
- characterId: hrnm
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09
- characterId: ttmr
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: ttmr
  produceId: produce-007
  stepType: ProduceStepType_AuditionMid2
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: ttmr
  produceId: produce-007
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-selection-audition-01
- characterId: ttmr
  produceId: produce-008
  stepType: ProduceStepType_AuditionMid1
  bgmAssetId: sud_bgm_produce_3rd-final-audition-03
- characterId: ttmr
  produceId: produce-008
  stepType: ProduceStepType_AuditionFinal
  bgmAssetId: sud_bgm_produce_3rd-final-audition-09