- id: producer_ranking_season-000
  name: シーズン0
  characterIds:
  - hski
  - ttmr
  - fktn
  - amao
  - hrnm
  - shro
  - kllj
  - ssmk
  - kcna
  - hume
  - hmsz
  - jsna
  hasCharacterRankingReward: true
  hasOverallRankingReward: false
  producerRankingRankGradeId: producer_ranking_rank_grade_season-000
  producerRankingProduceId: producer_ranking_produce-000
  producerRankingTowerId: producer_ranking_tower-000
  startTime: "1759716000000"
  endTime: "1766001600000"
  fixRankTime: "1766714400000"
- id: producer_ranking_season-001
  name: シーズン1
  characterIds:
  - hski
  - ttmr
  - fktn
  - amao
  - hrnm
  - shro
  - kllj
  - ssmk
  - kcna
  - hume
  - hmsz
  - jsna
  - atbm
  hasCharacterRankingReward: true
  hasOverallRankingReward: false
  producerRankingRankGradeId: producer_ranking_rank_grade_season-001
  producerRankingProduceId: producer_ranking_produce-001
  producerRankingTowerId: producer_ranking_tower-001
  startTime: "1766714400000"
  endTime: "1771185600000"
  fixRankTime: "1771466400000"