- characterId: amao
  characterTopPositionX: 0
  characterTopPositionY: 0
- characterId: atbm
  characterTopPositionX: 0
  characterTopPositionY: 0
- characterId: fktn
  characterTopPositionX: 0
  characterTopPositionY: 0
- characterId: hmsz
  characterTopPositionX: 0
  characterTopPositionY: 0
- characterId: hrnm
  characterTopPositionX: 0
  characterTopPositionY: 0
- characterId: hski
  characterTopPositionX: 0
  characterTopPositionY: 0
- characterId: hume
  characterTopPositionX: 0
  characterTopPositionY: 0
- characterId: jsna
  characterTopPositionX: 0
  characterTopPositionY: 0
- characterId: kcna
  characterTopPositionX: 0
  characterTopPositionY: 0
- characterId: kllj
  characterTopPositionX: 0
  characterTopPositionY: 0
- characterId: shro
  characterTopPositionX: 0
  characterTopPositionY: 0
- characterId: ssmk
  characterTopPositionX: 0
  characterTopPositionY: 0
- characterId: ttmr
  characterTopPositionX: 0
  characterTopPositionY: 0