- id: challenge_slot-exam_card_play_aggressive
  produceId: produce-003
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_card_play_aggressive-produce_003-group_001
  unlockDescription: ""
- id: challenge_slot-exam_card_play_aggressive
  produceId: produce-003
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_card_play_aggressive-produce_003-group_002
  unlockDescription: 「初」：マスターの最終試験で1位になる
- id: challenge_slot-exam_card_play_aggressive
  produceId: produce-003
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_card_play_aggressive-produce_003-group_003
  unlockDescription: 「初」：マスターでプロデュース評価Sを獲得する
- id: challenge_slot-exam_card_play_aggressive
  produceId: produce-005
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_card_play_aggressive-produce_005-group_001
  unlockDescription: ""
- id: challenge_slot-exam_card_play_aggressive
  produceId: produce-005
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_card_play_aggressive-produce_005-group_002
  unlockDescription: ""
- id: challenge_slot-exam_card_play_aggressive
  produceId: produce-005
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_card_play_aggressive-produce_005-group_003
  unlockDescription: ""
- id: challenge_slot-exam_card_play_aggressive
  produceId: produce-006
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_card_play_aggressive-produce_006-group_001
  unlockDescription: ""
- id: challenge_slot-exam_card_play_aggressive
  produceId: produce-006
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_card_play_aggressive-produce_006-group_002
  unlockDescription: ""
- id: challenge_slot-exam_card_play_aggressive
  produceId: produce-006
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_card_play_aggressive-produce_006-group_003
  unlockDescription: ""
- id: challenge_slot-exam_concentration
  produceId: produce-003
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_concentration-produce_003-group_001
  unlockDescription: ""
- id: challenge_slot-exam_concentration
  produceId: produce-003
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_concentration-produce_003-group_002
  unlockDescription: 「初」：マスターの最終試験で1位になる
- id: challenge_slot-exam_concentration
  produceId: produce-003
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_concentration-produce_003-group_003
  unlockDescription: 「初」：マスターでプロデュース評価Sを獲得する
- id: challenge_slot-exam_concentration
  produceId: produce-005
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_concentration-produce_005-group_001
  unlockDescription: ""
- id: challenge_slot-exam_concentration
  produceId: produce-005
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_concentration-produce_005-group_002
  unlockDescription: ""
- id: challenge_slot-exam_concentration
  produceId: produce-005
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_concentration-produce_005-group_003
  unlockDescription: ""
- id: challenge_slot-exam_concentration
  produceId: produce-006
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_concentration-produce_006-group_001
  unlockDescription: ""
- id: challenge_slot-exam_concentration
  produceId: produce-006
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_concentration-produce_006-group_002
  unlockDescription: ""
- id: challenge_slot-exam_concentration
  produceId: produce-006
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_concentration-produce_006-group_003
  unlockDescription: ""
- id: challenge_slot-exam_full_power
  produceId: produce-003
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_full_power-produce_003-group_001
  unlockDescription: ""
- id: challenge_slot-exam_full_power
  produceId: produce-003
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_full_power-produce_003-group_002
  unlockDescription: 「初」：マスターの最終試験で1位になる
- id: challenge_slot-exam_full_power
  produceId: produce-003
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_full_power-produce_003-group_003
  unlockDescription: 「初」：マスターでプロデュース評価Sを獲得する
- id: challenge_slot-exam_full_power
  produceId: produce-005
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_full_power-produce_005-group_001
  unlockDescription: ""
- id: challenge_slot-exam_full_power
  produceId: produce-005
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_full_power-produce_005-group_002
  unlockDescription: ""
- id: challenge_slot-exam_full_power
  produceId: produce-005
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_full_power-produce_005-group_003
  unlockDescription: ""
- id: challenge_slot-exam_full_power
  produceId: produce-006
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_full_power-produce_006-group_001
  unlockDescription: ""
- id: challenge_slot-exam_full_power
  produceId: produce-006
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_full_power-produce_006-group_002
  unlockDescription: ""
- id: challenge_slot-exam_full_power
  produceId: produce-006
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_full_power-produce_006-group_003
  unlockDescription: ""
- id: challenge_slot-exam_lesson_buff
  produceId: produce-003
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_lesson_buff-produce_003-group_001
  unlockDescription: ""
- id: challenge_slot-exam_lesson_buff
  produceId: produce-003
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_lesson_buff-produce_003-group_002
  unlockDescription: 「初」：マスターの最終試験で1位になる
- id: challenge_slot-exam_lesson_buff
  produceId: produce-003
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_lesson_buff-produce_003-group_003
  unlockDescription: 「初」：マスターでプロデュース評価Sを獲得する
- id: challenge_slot-exam_lesson_buff
  produceId: produce-005
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_lesson_buff-produce_005-group_001
  unlockDescription: ""
- id: challenge_slot-exam_lesson_buff
  produceId: produce-005
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_lesson_buff-produce_005-group_002
  unlockDescription: ""
- id: challenge_slot-exam_lesson_buff
  produceId: produce-005
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_lesson_buff-produce_005-group_003
  unlockDescription: ""
- id: challenge_slot-exam_lesson_buff
  produceId: produce-006
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_lesson_buff-produce_006-group_001
  unlockDescription: ""
- id: challenge_slot-exam_lesson_buff
  produceId: produce-006
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_lesson_buff-produce_006-group_002
  unlockDescription: ""
- id: challenge_slot-exam_lesson_buff
  produceId: produce-006
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_lesson_buff-produce_006-group_003
  unlockDescription: ""
- id: challenge_slot-exam_parameter_buff
  produceId: produce-003
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_parameter_buff-produce_003-group_001
  unlockDescription: ""
- id: challenge_slot-exam_parameter_buff
  produceId: produce-003
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_parameter_buff-produce_003-group_002
  unlockDescription: 「初」：マスターの最終試験で1位になる
- id: challenge_slot-exam_parameter_buff
  produceId: produce-003
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_parameter_buff-produce_003-group_003
  unlockDescription: 「初」：マスターでプロデュース評価Sを獲得する
- id: challenge_slot-exam_parameter_buff
  produceId: produce-005
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_parameter_buff-produce_005-group_001
  unlockDescription: ""
- id: challenge_slot-exam_parameter_buff
  produceId: produce-005
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_parameter_buff-produce_005-group_002
  unlockDescription: ""
- id: challenge_slot-exam_parameter_buff
  produceId: produce-005
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_parameter_buff-produce_005-group_003
  unlockDescription: ""
- id: challenge_slot-exam_parameter_buff
  produceId: produce-006
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_parameter_buff-produce_006-group_001
  unlockDescription: ""
- id: challenge_slot-exam_parameter_buff
  produceId: produce-006
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_parameter_buff-produce_006-group_002
  unlockDescription: ""
- id: challenge_slot-exam_parameter_buff
  produceId: produce-006
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_parameter_buff-produce_006-group_003
  unlockDescription: ""
- id: challenge_slot-exam_review
  produceId: produce-003
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_review-produce_003-group_001
  unlockDescription: ""
- id: challenge_slot-exam_review
  produceId: produce-003
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_review-produce_003-group_002
  unlockDescription: 「初」：マスターの最終試験で1位になる
- id: challenge_slot-exam_review
  produceId: produce-003
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_review-produce_003-group_003
  unlockDescription: 「初」：マスターでプロデュース評価Sを獲得する
- id: challenge_slot-exam_review
  produceId: produce-005
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_review-produce_005-group_001
  unlockDescription: ""
- id: challenge_slot-exam_review
  produceId: produce-005
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_review-produce_005-group_002
  unlockDescription: ""
- id: challenge_slot-exam_review
  produceId: produce-005
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_review-produce_005-group_003
  unlockDescription: ""
- id: challenge_slot-exam_review
  produceId: produce-006
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_review-produce_006-group_001
  unlockDescription: ""
- id: challenge_slot-exam_review
  produceId: produce-006
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_review-produce_006-group_002
  unlockDescription: ""
- id: challenge_slot-exam_review
  produceId: produce-006
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_review-produce_006-group_003
  unlockDescription: ""