- produceId: produce-006
  examEffectType: ProduceExamEffectType_ExamParameterBuff
  produceCardIds:
  - p_card-01-act-100_004
  - p_card-01-men-100_001
  - p_card-01-men-100_005
- produceId: produce-006
  examEffectType: ProduceExamEffectType_ExamLessonBuff
  produceCardIds:
  - p_card-01-act-100_004
  - p_card-01-men-100_001
  - p_card-01-men-100_005
- produceId: produce-006
  examEffectType: ProduceExamEffectType_ExamReview
  produceCardIds:
  - p_card-02-men-100_007
  - p_card-02-men-100_008
  - p_card-02-men-100_011
- produceId: produce-006
  examEffectType: ProduceExamEffectType_ExamCardPlayAggressive
  produceCardIds:
  - p_card-02-men-100_007
  - p_card-02-men-100_008
  - p_card-02-men-100_011
- produceId: produce-006
  examEffectType: ProduceExamEffectType_ExamConcentration
  produceCardIds:
  - p_card-03-act-100_013
  - p_card-03-men-100_015
  - p_card-03-men-100_016
- produceId: produce-006
  examEffectType: ProduceExamEffectType_ExamFullPower
  produceCardIds:
  - p_card-03-act-100_013
  - p_card-03-men-100_015
  - p_card-03-men-100_016