- id: p_setting-1
  initialProducePoint: 0
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700
  customizeProduceCardCount: 1
  stepSkipStaminaRecoveryPermil: 250
  beforeAuditionRefreshStaminaRecoveryPermil: 700
  stepCustomizeStartAlertProducePointThreshold: 49
  examStartAlertStaminaThreshold: 10
  continueCount: 3
  produceAuditionTrendAssessmentPermil: 200
- id: p_setting-2
  initialProducePoint: 0
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700
  customizeProduceCardCount: 1
  stepSkipStaminaRecoveryPermil: 250
  beforeAuditionRefreshStaminaRecoveryPermil: 700
  stepCustomizeStartAlertProducePointThreshold: 49
  examStartAlertStaminaThreshold: 10
  continueCount: 3
  produceAuditionTrendAssessmentPermil: 200
- id: p_setting-3
  initialProducePoint: 0
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700
  customizeProduceCardCount: 1
  stepSkipStaminaRecoveryPermil: 250
  beforeAuditionRefreshStaminaRecoveryPermil: 700
  stepCustomizeStartAlertProducePointThreshold: 49
  examStartAlertStaminaThreshold: 10
  continueCount: 3
  produceAuditionTrendAssessmentPermil: 200