- id: p_step_open_lesson-produce_007-01-parameter-sp-sub_da
  stamina: 8
  subParameterType: ProduceParameterType_Dance
  mainParameter: 80
  subParameter: 50
  star: 10
- id: p_step_open_lesson-produce_007-01-parameter-sp-sub_vi
  stamina: 8
  subParameterType: ProduceParameterType_Visual
  mainParameter: 80
  subParameter: 50
  star: 10
- id: p_step_open_lesson-produce_007-01-parameter-sp-sub_vo
  stamina: 8
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 80
  subParameter: 50
  star: 10
- id: p_step_open_lesson-produce_007-01-parameter-sub_da
  stamina: 6
  subParameterType: ProduceParameterType_Dance
  mainParameter: 60
  subParameter: 20
  star: 5
- id: p_step_open_lesson-produce_007-01-parameter-sub_vi
  stamina: 6
  subParameterType: ProduceParameterType_Visual
  mainParameter: 60
  subParameter: 20
  star: 5
- id: p_step_open_lesson-produce_007-01-parameter-sub_vo
  stamina: 6
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 60
  subParameter: 20
  star: 5
- id: p_step_open_lesson-produce_007-01-star-sp-sub_da
  stamina: 8
  subParameterType: ProduceParameterType_Dance
  mainParameter: 60
  subParameter: 20
  star: 30
- id: p_step_open_lesson-produce_007-01-star-sp-sub_vi
  stamina: 8
  subParameterType: ProduceParameterType_Visual
  mainParameter: 60
  subParameter: 20
  star: 30
- id: p_step_open_lesson-produce_007-01-star-sp-sub_vo
  stamina: 8
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 60
  subParameter: 20
  star: 30
- id: p_step_open_lesson-produce_007-01-star-sub_da
  stamina: 6
  subParameterType: ProduceParameterType_Dance
  mainParameter: 50
  subParameter: 10
  star: 20
- id: p_step_open_lesson-produce_007-01-star-sub_vi
  stamina: 6
  subParameterType: ProduceParameterType_Visual
  mainParameter: 50
  subParameter: 10
  star: 20
- id: p_step_open_lesson-produce_007-01-star-sub_vo
  stamina: 6
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 50
  subParameter: 10
  star: 20
- id: p_step_open_lesson-produce_007-02-parameter-sp-sub_da
  stamina: 8
  subParameterType: ProduceParameterType_Dance
  mainParameter: 100
  subParameter: 60
  star: 10
- id: p_step_open_lesson-produce_007-02-parameter-sp-sub_vi
  stamina: 8
  subParameterType: ProduceParameterType_Visual
  mainParameter: 100
  subParameter: 60
  star: 10
- id: p_step_open_lesson-produce_007-02-parameter-sp-sub_vo
  stamina: 8
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 100
  subParameter: 60
  star: 10
- id: p_step_open_lesson-produce_007-02-parameter-sub_da
  stamina: 6
  subParameterType: ProduceParameterType_Dance
  mainParameter: 80
  subParameter: 30
  star: 5
- id: p_step_open_lesson-produce_007-02-parameter-sub_vi
  stamina: 6
  subParameterType: ProduceParameterType_Visual
  mainParameter: 80
  subParameter: 30
  star: 5
- id: p_step_open_lesson-produce_007-02-parameter-sub_vo
  stamina: 6
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 80
  subParameter: 30
  star: 5
- id: p_step_open_lesson-produce_007-02-star-sp-sub_da
  stamina: 8
  subParameterType: ProduceParameterType_Dance
  mainParameter: 80
  subParameter: 20
  star: 30
- id: p_step_open_lesson-produce_007-02-star-sp-sub_vi
  stamina: 8
  subParameterType: ProduceParameterType_Visual
  mainParameter: 80
  subParameter: 20
  star: 30
- id: p_step_open_lesson-produce_007-02-star-sp-sub_vo
  stamina: 8
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 80
  subParameter: 20
  star: 30
- id: p_step_open_lesson-produce_007-02-star-sub_da
  stamina: 6
  subParameterType: ProduceParameterType_Dance
  mainParameter: 70
  subParameter: 10
  star: 20
- id: p_step_open_lesson-produce_007-02-star-sub_vi
  stamina: 6
  subParameterType: ProduceParameterType_Visual
  mainParameter: 70
  subParameter: 10
  star: 20
- id: p_step_open_lesson-produce_007-02-star-sub_vo
  stamina: 6
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 70
  subParameter: 10
  star: 20
- id: p_step_open_lesson-produce_007-03-parameter-sp-sub_da
  stamina: 8
  subParameterType: ProduceParameterType_Dance
  mainParameter: 120
  subParameter: 70
  star: 10
- id: p_step_open_lesson-produce_007-03-parameter-sp-sub_vi
  stamina: 8
  subParameterType: ProduceParameterType_Visual
  mainParameter: 120
  subParameter: 70
  star: 10
- id: p_step_open_lesson-produce_007-03-parameter-sp-sub_vo
  stamina: 8
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 120
  subParameter: 70
  star: 10
- id: p_step_open_lesson-produce_007-03-parameter-sub_da
  stamina: 6
  subParameterType: ProduceParameterType_Dance
  mainParameter: 100
  subParameter: 40
  star: 5
- id: p_step_open_lesson-produce_007-03-parameter-sub_vi
  stamina: 6
  subParameterType: ProduceParameterType_Visual
  mainParameter: 100
  subParameter: 40
  star: 5
- id: p_step_open_lesson-produce_007-03-parameter-sub_vo
  stamina: 6
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 100
  subParameter: 40
  star: 5
- id: p_step_open_lesson-produce_007-03-star-sp-sub_da
  stamina: 8
  subParameterType: ProduceParameterType_Dance
  mainParameter: 100
  subParameter: 20
  star: 30
- id: p_step_open_lesson-produce_007-03-star-sp-sub_vi
  stamina: 8
  subParameterType: ProduceParameterType_Visual
  mainParameter: 100
  subParameter: 20
  star: 30
- id: p_step_open_lesson-produce_007-03-star-sp-sub_vo
  stamina: 8
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 100
  subParameter: 20
  star: 30
- id: p_step_open_lesson-produce_007-03-star-sub_da
  stamina: 6
  subParameterType: ProduceParameterType_Dance
  mainParameter: 90
  subParameter: 10
  star: 20
- id: p_step_open_lesson-produce_007-03-star-sub_vi
  stamina: 6
  subParameterType: ProduceParameterType_Visual
  mainParameter: 90
  subParameter: 10
  star: 20
- id: p_step_open_lesson-produce_007-03-star-sub_vo
  stamina: 6
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 90
  subParameter: 10
  star: 20
- id: p_step_open_lesson-produce_007-04-parameter-sp-sub_da
  stamina: 8
  subParameterType: ProduceParameterType_Dance
  mainParameter: 140
  subParameter: 80
  star: 10
- id: p_step_open_lesson-produce_007-04-parameter-sp-sub_vi
  stamina: 8
  subParameterType: ProduceParameterType_Visual
  mainParameter: 140
  subParameter: 80
  star: 10
- id: p_step_open_lesson-produce_007-04-parameter-sp-sub_vo
  stamina: 8
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 140
  subParameter: 80
  star: 10
- id: p_step_open_lesson-produce_007-04-parameter-sub_da
  stamina: 6
  subParameterType: ProduceParameterType_Dance
  mainParameter: 120
  subParameter: 50
  star: 5
- id: p_step_open_lesson-produce_007-04-parameter-sub_vi
  stamina: 6
  subParameterType: ProduceParameterType_Visual
  mainParameter: 120
  subParameter: 50
  star: 5
- id: p_step_open_lesson-produce_007-04-parameter-sub_vo
  stamina: 6
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 120
  subParameter: 50
  star: 5
- id: p_step_open_lesson-produce_007-04-star-sp-sub_da
  stamina: 8
  subParameterType: ProduceParameterType_Dance
  mainParameter: 120
  subParameter: 20
  star: 30
- id: p_step_open_lesson-produce_007-04-star-sp-sub_vi
  stamina: 8
  subParameterType: ProduceParameterType_Visual
  mainParameter: 120
  subParameter: 20
  star: 30
- id: p_step_open_lesson-produce_007-04-star-sp-sub_vo
  stamina: 8
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 120
  subParameter: 20
  star: 30
- id: p_step_open_lesson-produce_007-04-star-sub_da
  stamina: 6
  subParameterType: ProduceParameterType_Dance
  mainParameter: 110
  subParameter: 10
  star: 20
- id: p_step_open_lesson-produce_007-04-star-sub_vi
  stamina: 6
  subParameterType: ProduceParameterType_Visual
  mainParameter: 110
  subParameter: 10
  star: 20
- id: p_step_open_lesson-produce_007-04-star-sub_vo
  stamina: 6
  subParameterType: ProduceParameterType_Vocal
  mainParameter: 110
  subParameter: 10
  star: 20