- id: jsna
  produceCharacterId: amao
  stepType: ProduceStepType_AuditionFinal
  number: 1
  actorAssetIds:
  - mdl_chr_jsna-cstm-0110_body
  - mdl_chr_jsna-base-0000_hair
  - mdl_chr_jsna-base-0000_face
  produceIds:
  - produce-008
- id: jsna
  produceCharacterId: hmsz
  stepType: ProduceStepType_AuditionFinal
  number: 1
  actorAssetIds:
  - mdl_chr_jsna-cstm-0110_body
  - mdl_chr_jsna-base-0000_hair
  - mdl_chr_jsna-base-0000_face
  produceIds:
  - produce-008
- id: jsna
  produceCharacterId: hrnm
  stepType: ProduceStepType_AuditionFinal
  number: 1
  actorAssetIds:
  - mdl_chr_jsna-cstm-0110_body
  - mdl_chr_jsna-base-0000_hair
  - mdl_chr_jsna-base-0000_face
  produceIds:
  - produce-008
- id: jsna
  produceCharacterId: ttmr
  stepType: ProduceStepType_AuditionFinal
  number: 1
  actorAssetIds:
  - mdl_chr_jsna-cstm-0110_body
  - mdl_chr_jsna-base-0000_hair
  - mdl_chr_jsna-base-0000_face
  produceIds:
  - produce-008