- produceId: produce-003
  characterId: amao
  unlockConditionSetId: cd-dearness_level-amao-10
- produceId: produce-003
  characterId: fktn
  unlockConditionSetId: cd-dearness_level-fktn-10
- produceId: produce-003
  characterId: hrnm
  unlockConditionSetId: cd-dearness_level-hrnm-10
- produceId: produce-003
  characterId: hski
  unlockConditionSetId: cd-dearness_level-hski-10
- produceId: produce-003
  characterId: hume
  unlockConditionSetId: cd-dearness_level-hume-10
- produceId: produce-003
  characterId: kcna
  unlockConditionSetId: cd-dearness_level-kcna-10
- produceId: produce-003
  characterId: kllj
  unlockConditionSetId: cd-dearness_level-kllj-10
- produceId: produce-003
  characterId: shro
  unlockConditionSetId: cd-dearness_level-shro-10
- produceId: produce-003
  characterId: ssmk
  unlockConditionSetId: cd-dearness_level-ssmk-10
- produceId: produce-003
  characterId: ttmr
  unlockConditionSetId: cd-dearness_level-ttmr-10