- id: producer_ranking_season-000
  name: シーズン0
  characterIds:
  - hski
  - ttmr
  - fktn
  - amao
  - hrnm
  - shro
  - kllj
  - ssmk
  - kcna
  - hume
  - hmsz
  - jsna
  hasCharacterRankingReward: true
  hasOverallRankingReward: false
  producerRankingRankGradeId: producer_ranking_rank_grade_season-000
  producerRankingProduceId: producer_ranking_produce-000
  producerRankingTowerId: producer_ranking_tower-000
  startTime: "1759716000000"
  endTime: "1766001600000"
  fixRankTime: "1766714400000"
- id: producer_ranking_season-001
  name: シーズン1
  characterIds:
  - hski
  - ttmr
  - fktn
  - amao
  - hrnm
  - shro
  - kllj
  - ssmk
  - kcna
  - hume
  - hmsz
  - jsna
  - atbm
  hasCharacterRankingReward: true
  hasOverallRankingReward: false
  producerRankingRankGradeId: producer_ranking_rank_grade_season-001
  producerRankingProduceId: producer_ranking_produce-001
  producerRankingTowerId: producer_ranking_tower-001
  startTime: "1766714400000"
  endTime: "1771185600000"
  fixRankTime: "1771466400000"
- id: producer_ranking_season-002
  name: シーズン2
  characterIds:
  - hski
  - ttmr
  - fktn
  - amao
  - hrnm
  - shro
  - kllj
  - ssmk
  - kcna
  - hume
  - hmsz
  - jsna
  - atbm
  hasCharacterRankingReward: true
  hasOverallRankingReward: false
  producerRankingRankGradeId: producer_ranking_rank_grade_season-002
  producerRankingProduceId: producer_ranking_produce-002
  producerRankingTowerId: producer_ranking_tower-002
  startTime: "1773021600000"
  endTime: "1778615999000"
  fixRankTime: "1778896799000"
- id: producer_ranking_season-003
  name: シーズン3
  characterIds:
  - hski
  - ttmr
  - fktn
  - atbm
  - amao
  - kllj
  - kcna
  - ssmk
  - shro
  - jsna
  - hmsz
  - hume
  - hrnm
  hasCharacterRankingReward: true
  hasOverallRankingReward: false
  producerRankingRankGradeId: producer_ranking_rank_grade_season-003
  producerRankingProduceId: producer_ranking_produce-003
  producerRankingTowerId: producer_ranking_tower-003
  startTime: "1779069600000"
  endTime: "1788033599000"
  fixRankTime: "1788314399000"
- id: producer_ranking_season-004
  name: シーズン4
  characterIds:
  - hski
  - ttmr
  - fktn
  - atbm
  - amao
  - kllj
  - kcna
  - ssmk
  - shro
  - jsna
  - hmsz
  - hume
  - hrnm
  hasCharacterRankingReward: true
  hasOverallRankingReward: false
  producerRankingRankGradeId: producer_ranking_rank_grade_season-004
  producerRankingProduceId: producer_ranking_produce-004
  producerRankingTowerId: producer_ranking_tower-004
  startTime: "1789005600000"
  endTime: "1794427199000"
  fixRankTime: "1794707999000"