- rivalActorId: hume
  motionType: ProduceStepAuditionMotionType_PreResult
  number: 1
  bodyAssetId: mot_aud_chr_cmmn_cmmn-hif-final02-result-score-rival-002_in
  facialAssetId: ""
- rivalActorId: jsna
  motionType: ProduceStepAuditionMotionType_PreResult
  number: 1
  bodyAssetId: mot_aud_chr_cmmn_cmmn-hif-final02-result-score-rival-001_in
  facialAssetId: ""