- id: p_setting-1
  initialProducePoint: 0
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700
  customizeProduceCardCount: 1
  stepSkipStaminaRecoveryPermil: 250
  beforeAuditionRefreshStaminaRecoveryPermil: 700
  stepCustomizeStartAlertProducePointThreshold: 49
  examStartAlertStaminaThreshold: 10
  continueCount: 3
  produceAuditionTrendAssessmentPermilUpper: 200
  produceAuditionTrendAssessmentPermilLower: 200
  produceAuditionTrendAssessmentPermil: 0
- id: p_setting-2
  initialProducePoint: 0
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700
  customizeProduceCardCount: 1
  stepSkipStaminaRecoveryPermil: 250
  beforeAuditionRefreshStaminaRecoveryPermil: 700
  stepCustomizeStartAlertProducePointThreshold: 49
  examStartAlertStaminaThreshold: 10
  continueCount: 3
  produceAuditionTrendAssessmentPermilUpper: 200
  produceAuditionTrendAssessmentPermilLower: 200
  produceAuditionTrendAssessmentPermil: 0
- id: p_setting-3
  initialProducePoint: 0
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700
  customizeProduceCardCount: 1
  stepSkipStaminaRecoveryPermil: 250
  beforeAuditionRefreshStaminaRecoveryPermil: 700
  stepCustomizeStartAlertProducePointThreshold: 49
  examStartAlertStaminaThreshold: 10
  continueCount: 3
  produceAuditionTrendAssessmentPermilUpper: 200
  produceAuditionTrendAssessmentPermilLower: 200
  produceAuditionTrendAssessmentPermil: 0
- id: p_setting-4
  initialProducePoint: 0
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700
  customizeProduceCardCount: 1
  stepSkipStaminaRecoveryPermil: 250
  beforeAuditionRefreshStaminaRecoveryPermil: 500
  stepCustomizeStartAlertProducePointThreshold: 39
  examStartAlertStaminaThreshold: 10
  continueCount: 3
  produceAuditionTrendAssessmentPermilUpper: 200
  produceAuditionTrendAssessmentPermilLower: 200
  produceAuditionTrendAssessmentPermil: 0
- id: p_setting-5
  initialProducePoint: 0
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700
  customizeProduceCardCount: 2
  stepSkipStaminaRecoveryPermil: 250
  beforeAuditionRefreshStaminaRecoveryPermil: 500
  stepCustomizeStartAlertProducePointThreshold: 39
  examStartAlertStaminaThreshold: 10
  continueCount: 3
  produceAuditionTrendAssessmentPermilUpper: 110
  produceAuditionTrendAssessmentPermilLower: 110
  produceAuditionTrendAssessmentPermil: 0