- environmentAssetId: env_3d_live_amao001-00-noon
  musicId: music-char-amao-001
  thumbnailAssetId: img_general_live_music-char-amao-001_true-end
  timelineAssetId: tln_live_amao-001
  type: ProduceLiveType_TrueEnd
- afterAdvAssetId: adv_live_amao_001_end-01-01
  beforeAdvAssetId: adv_live_amao_001_start-01-01
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  musicId: music-char-amao-001
  thumbnailAssetId: img_general_live_music-char-amao-001_a
  timelineAssetId: tln_live_amao-001-normal-001
  type: ProduceLiveType_A
- afterAdvAssetId: adv_live_amao_001_end-02-01
  beforeAdvAssetId: adv_live_amao_001_start-02-01
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  musicId: music-char-amao-001
  thumbnailAssetId: img_general_live_music-char-amao-001_b
  timelineAssetId: tln_live_amao-001-normal-002
  type: ProduceLiveType_B
- afterAdvAssetId: adv_live_amao_001_end-03-01
  beforeAdvAssetId: adv_live_amao_001_start-03-01
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  musicId: music-char-amao-001
  thumbnailAssetId: img_general_live_music-char-amao-001_c
  timelineAssetId: tln_live_amao-001-normal-003
  type: ProduceLiveType_C
- afterAdvAssetId: adv_live_amao_001_end-04-01
  beforeAdvAssetId: adv_live_amao_001_start-04-01
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  musicId: music-char-amao-001
  thumbnailAssetId: img_general_live_music-char-amao-001_d
  timelineAssetId: tln_live_amao-001-normal-004
  type: ProduceLiveType_D
- environmentAssetId: env_3d_live_fktn001-00-noon
  musicId: music-char-fktn-001
  thumbnailAssetId: img_general_live_music-char-fktn-001_true-end
  timelineAssetId: tln_live_fktn-001
  type: ProduceLiveType_TrueEnd
- afterAdvAssetId: adv_live_fktn_001_end-01-01
  beforeAdvAssetId: adv_live_fktn_001_start-01-01
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  musicId: music-char-fktn-001
  thumbnailAssetId: img_general_live_music-char-fktn-001_a
  timelineAssetId: tln_live_fktn-001-normal-001
  type: ProduceLiveType_A
- afterAdvAssetId: adv_live_fktn_001_end-02-01
  beforeAdvAssetId: adv_live_fktn_001_start-02-01
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  musicId: music-char-fktn-001
  thumbnailAssetId: img_general_live_music-char-fktn-001_b
  timelineAssetId: tln_live_fktn-001-normal-002
  type: ProduceLiveType_B
- afterAdvAssetId: adv_live_fktn_001_end-03-01
  beforeAdvAssetId: adv_live_fktn_001_start-03-01
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  musicId: music-char-fktn-001
  thumbnailAssetId: img_general_live_music-char-fktn-001_c
  timelineAssetId: tln_live_fktn-001-normal-003
  type: ProduceLiveType_C
- afterAdvAssetId: adv_live_fktn_001_end-04-01
  beforeAdvAssetId: adv_live_fktn_001_start-04-01
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  musicId: music-char-fktn-001
  thumbnailAssetId: img_general_live_music-char-fktn-001_d
  timelineAssetId: tln_live_fktn-001-normal-004
  type: ProduceLiveType_D
- environmentAssetId: env_3d_live_hrnm001-00-noon
  musicId: music-char-hrnm-001
  thumbnailAssetId: img_general_live_music-char-hrnm-001_true-end
  timelineAssetId: tln_live_hrnm-001
  type: ProduceLiveType_TrueEnd
- afterAdvAssetId: adv_live_hrnm_001_end-01-01
  beforeAdvAssetId: adv_live_hrnm_001_start-01-01
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  musicId: music-char-hrnm-001
  thumbnailAssetId: img_general_live_music-char-hrnm-001_a
  timelineAssetId: tln_live_hrnm-001-normal-001
  type: ProduceLiveType_A
- afterAdvAssetId: adv_live_hrnm_001_end-02-01
  beforeAdvAssetId: adv_live_hrnm_001_start-02-01
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  musicId: music-char-hrnm-001
  thumbnailAssetId: img_general_live_music-char-hrnm-001_b
  timelineAssetId: tln_live_hrnm-001-normal-002
  type: ProduceLiveType_B
- afterAdvAssetId: adv_live_hrnm_001_end-03-01
  beforeAdvAssetId: adv_live_hrnm_001_start-03-01
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  musicId: music-char-hrnm-001
  thumbnailAssetId: img_general_live_music-char-hrnm-001_c
  timelineAssetId: tln_live_hrnm-001-normal-003
  type: ProduceLiveType_C
- afterAdvAssetId: adv_live_hrnm_001_end-04-01
  beforeAdvAssetId: adv_live_hrnm_001_start-04-01
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  musicId: music-char-hrnm-001
  thumbnailAssetId: img_general_live_music-char-hrnm-001_d
  timelineAssetId: tln_live_hrnm-001-normal-004
  type: ProduceLiveType_D
- environmentAssetId: env_3d_live_hski001-00-noon
  musicId: music-char-hski-001
  thumbnailAssetId: img_general_live_music-char-hski-001_true-end
  timelineAssetId: tln_live_hski-001
  type: ProduceLiveType_TrueEnd
- afterAdvAssetId: adv_live_hski_001_end-01-01
  beforeAdvAssetId: adv_live_hski_001_start-01-01
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  musicId: music-char-hski-001
  thumbnailAssetId: img_general_live_music-char-hski-001_a
  timelineAssetId: tln_live_hski-001-normal-001
  type: ProduceLiveType_A
- afterAdvAssetId: adv_live_hski_001_end-02-01
  beforeAdvAssetId: adv_live_hski_001_start-02-01
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  musicId: music-char-hski-001
  thumbnailAssetId: img_general_live_music-char-hski-001_b
  timelineAssetId: tln_live_hski-001-normal-002
  type: ProduceLiveType_B
- afterAdvAssetId: adv_live_hski_001_end-03-01
  beforeAdvAssetId: adv_live_hski_001_start-03-01
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  musicId: music-char-hski-001
  thumbnailAssetId: img_general_live_music-char-hski-001_c
  timelineAssetId: tln_live_hski-001-normal-003
  type: ProduceLiveType_C
- afterAdvAssetId: adv_live_hski_001_end-04-01
  beforeAdvAssetId: adv_live_hski_001_start-04-01
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  musicId: music-char-hski-001
  thumbnailAssetId: img_general_live_music-char-hski-001_d
  timelineAssetId: tln_live_hski-001-normal-004
  type: ProduceLiveType_D
- environmentAssetId: env_3d_live_kcna001-00-noon
  musicId: music-char-kcna-001
  thumbnailAssetId: img_general_live_music-char-kcna-001_true-end
  timelineAssetId: tln_live_kcna-001
  type: ProduceLiveType_TrueEnd
- afterAdvAssetId: adv_live_kcna_001_end-01-01
  beforeAdvAssetId: adv_live_kcna_001_start-01-01
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  musicId: music-char-kcna-001
  thumbnailAssetId: img_general_live_music-char-kcna-001_a
  timelineAssetId: tln_live_kcna-001-normal-001
  type: ProduceLiveType_A
- afterAdvAssetId: adv_live_kcna_001_end-02-01
  beforeAdvAssetId: adv_live_kcna_001_start-02-01
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  musicId: music-char-kcna-001
  thumbnailAssetId: img_general_live_music-char-kcna-001_b
  timelineAssetId: tln_live_kcna-001-normal-002
  type: ProduceLiveType_B
- afterAdvAssetId: adv_live_kcna_001_end-03-01
  beforeAdvAssetId: adv_live_kcna_001_start-03-01
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  musicId: music-char-kcna-001
  thumbnailAssetId: img_general_live_music-char-kcna-001_c
  timelineAssetId: tln_live_kcna-001-normal-003
  type: ProduceLiveType_C
- afterAdvAssetId: adv_live_kcna_001_end-04-01
  beforeAdvAssetId: adv_live_kcna_001_start-04-01
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  musicId: music-char-kcna-001
  thumbnailAssetId: img_general_live_music-char-kcna-001_d
  timelineAssetId: tln_live_kcna-001-normal-004
  type: ProduceLiveType_D
- environmentAssetId: env_3d_live_kllj001-00-noon
  musicId: music-char-kllj-001
  thumbnailAssetId: img_general_live_music-char-kllj-001_true-end
  timelineAssetId: tln_live_kllj-001
  type: ProduceLiveType_TrueEnd
- afterAdvAssetId: adv_live_kllj_001_end-01-01
  beforeAdvAssetId: adv_live_kllj_001_start-01-01
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  musicId: music-char-kllj-001
  thumbnailAssetId: img_general_live_music-char-kllj-001_a
  timelineAssetId: tln_live_kllj-001-normal-001
  type: ProduceLiveType_A
- afterAdvAssetId: adv_live_kllj_001_end-02-01
  beforeAdvAssetId: adv_live_kllj_001_start-02-01
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  musicId: music-char-kllj-001
  thumbnailAssetId: img_general_live_music-char-kllj-001_b
  timelineAssetId: tln_live_kllj-001-normal-002
  type: ProduceLiveType_B
- afterAdvAssetId: adv_live_kllj_001_end-03-01
  beforeAdvAssetId: adv_live_kllj_001_start-03-01
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  musicId: music-char-kllj-001
  thumbnailAssetId: img_general_live_music-char-kllj-001_c
  timelineAssetId: tln_live_kllj-001-normal-003
  type: ProduceLiveType_C
- afterAdvAssetId: adv_live_kllj_001_end-04-01
  beforeAdvAssetId: adv_live_kllj_001_start-04-01
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  musicId: music-char-kllj-001
  thumbnailAssetId: img_general_live_music-char-kllj-001_d
  timelineAssetId: tln_live_kllj-001-normal-004
  type: ProduceLiveType_D
- environmentAssetId: env_3d_live_shro001-00-noon
  musicId: music-char-shro-001
  thumbnailAssetId: img_general_live_music-char-shro-001_true-end
  timelineAssetId: tln_live_shro-001
  type: ProduceLiveType_TrueEnd
- afterAdvAssetId: adv_live_shro_001_end-01-01
  beforeAdvAssetId: adv_live_shro_001_start-01-01
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  musicId: music-char-shro-001
  thumbnailAssetId: img_general_live_music-char-shro-001_a
  timelineAssetId: tln_live_shro-001-normal-001
  type: ProduceLiveType_A
- afterAdvAssetId: adv_live_shro_001_end-02-01
  beforeAdvAssetId: adv_live_shro_001_start-02-01
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  musicId: music-char-shro-001
  thumbnailAssetId: img_general_live_music-char-shro-001_b
  timelineAssetId: tln_live_shro-001-normal-002
  type: ProduceLiveType_B
- afterAdvAssetId: adv_live_shro_001_end-03-01
  beforeAdvAssetId: adv_live_shro_001_start-03-01
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  musicId: music-char-shro-001
  thumbnailAssetId: img_general_live_music-char-shro-001_c
  timelineAssetId: tln_live_shro-001-normal-003
  type: ProduceLiveType_C
- afterAdvAssetId: adv_live_shro_001_end-04-01
  beforeAdvAssetId: adv_live_shro_001_start-04-01
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  musicId: music-char-shro-001
  thumbnailAssetId: img_general_live_music-char-shro-001_d
  timelineAssetId: tln_live_shro-001-normal-004
  type: ProduceLiveType_D
- environmentAssetId: env_3d_live_ssmk001-00-noon
  musicId: music-char-ssmk-001
  thumbnailAssetId: img_general_live_music-char-ssmk-001_true-end
  timelineAssetId: tln_live_ssmk-001
  type: ProduceLiveType_TrueEnd
- afterAdvAssetId: adv_live_ssmk_001_end-01-01
  beforeAdvAssetId: adv_live_ssmk_001_start-01-01
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  musicId: music-char-ssmk-001
  thumbnailAssetId: img_general_live_music-char-ssmk-001_a
  timelineAssetId: tln_live_ssmk-001-normal-001
  type: ProduceLiveType_A
- afterAdvAssetId: adv_live_ssmk_001_end-02-01
  beforeAdvAssetId: adv_live_ssmk_001_start-02-01
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  musicId: music-char-ssmk-001
  thumbnailAssetId: img_general_live_music-char-ssmk-001_b
  timelineAssetId: tln_live_ssmk-001-normal-002
  type: ProduceLiveType_B
- afterAdvAssetId: adv_live_ssmk_001_end-03-01
  beforeAdvAssetId: adv_live_ssmk_001_start-03-01
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  musicId: music-char-ssmk-001
  thumbnailAssetId: img_general_live_music-char-ssmk-001_c
  timelineAssetId: tln_live_ssmk-001-normal-003
  type: ProduceLiveType_C
- afterAdvAssetId: adv_live_ssmk_001_end-04-01
  beforeAdvAssetId: adv_live_ssmk_001_start-04-01
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  musicId: music-char-ssmk-001
  thumbnailAssetId: img_general_live_music-char-ssmk-001_d
  timelineAssetId: tln_live_ssmk-001-normal-004
  type: ProduceLiveType_D
- environmentAssetId: env_3d_live_ttmr001-00-noon
  musicId: music-char-ttmr-001
  thumbnailAssetId: img_general_live_music-char-ttmr-001_true-end
  timelineAssetId: tln_live_ttmr-001
  type: ProduceLiveType_TrueEnd
- afterAdvAssetId: adv_live_ttmr_001_end-01-01
  beforeAdvAssetId: adv_live_ttmr_001_start-01-01
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  musicId: music-char-ttmr-001
  thumbnailAssetId: img_general_live_music-char-ttmr-001_a
  timelineAssetId: tln_live_ttmr-001-normal-001
  type: ProduceLiveType_A
- afterAdvAssetId: adv_live_ttmr_001_end-02-01
  beforeAdvAssetId: adv_live_ttmr_001_start-02-01
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  musicId: music-char-ttmr-001
  thumbnailAssetId: img_general_live_music-char-ttmr-001_b
  timelineAssetId: tln_live_ttmr-001-normal-002
  type: ProduceLiveType_B
- afterAdvAssetId: adv_live_ttmr_001_end-03-01
  beforeAdvAssetId: adv_live_ttmr_001_start-03-01
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  musicId: music-char-ttmr-001
  thumbnailAssetId: img_general_live_music-char-ttmr-001_c
  timelineAssetId: tln_live_ttmr-001-normal-003
  type: ProduceLiveType_C
- afterAdvAssetId: adv_live_ttmr_001_end-04-01
  beforeAdvAssetId: adv_live_ttmr_001_start-04-01
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  musicId: music-char-ttmr-001
  thumbnailAssetId: img_general_live_music-char-ttmr-001_d
  timelineAssetId: tln_live_ttmr-001-normal-004
  type: ProduceLiveType_D