- produceGroupId: produce_group-001
  grade: ResultGrade_F
  threshold: 0
- produceGroupId: produce_group-001
  grade: ResultGrade_E
  threshold: 1000
- produceGroupId: produce_group-001
  grade: ResultGrade_D
  threshold: 2000
- produceGroupId: produce_group-001
  grade: ResultGrade_C
  threshold: 3000
- produceGroupId: produce_group-001
  grade: ResultGrade_CPlus
  threshold: 4500
- produceGroupId: produce_group-001
  grade: ResultGrade_B
  threshold: 6000
- produceGroupId: produce_group-001
  grade: ResultGrade_BPlus
  threshold: 8000
- produceGroupId: produce_group-001
  grade: ResultGrade_A
  threshold: 10000
- produceGroupId: produce_group-001
  grade: ResultGrade_APlus
  threshold: 11500
- produceGroupId: produce_group-001
  grade: ResultGrade_S
  threshold: 13000
- produceGroupId: produce_group-001
  grade: ResultGrade_SPlus
  threshold: 14500
- produceGroupId: produce_group-001
  grade: ResultGrade_Ss
  threshold: 16000
- produceGroupId: produce_group-001
  grade: ResultGrade_SsPlus
  threshold: 18000
- produceGroupId: produce_group-001
  grade: ResultGrade_Sss
  threshold: 20000
- produceGroupId: produce_group-001
  grade: ResultGrade_SssPlus
  threshold: 23000
- produceGroupId: produce_group-002
  grade: ResultGrade_F
  threshold: 0
- produceGroupId: produce_group-002
  grade: ResultGrade_E
  threshold: 1000
- produceGroupId: produce_group-002
  grade: ResultGrade_D
  threshold: 2000
- produceGroupId: produce_group-002
  grade: ResultGrade_C
  threshold: 3000
- produceGroupId: produce_group-002
  grade: ResultGrade_CPlus
  threshold: 4500
- produceGroupId: produce_group-002
  grade: ResultGrade_B
  threshold: 6000
- produceGroupId: produce_group-002
  grade: ResultGrade_BPlus
  threshold: 8000
- produceGroupId: produce_group-002
  grade: ResultGrade_A
  threshold: 10000
- produceGroupId: produce_group-002
  grade: ResultGrade_APlus
  threshold: 11500
- produceGroupId: produce_group-002
  grade: ResultGrade_S
  threshold: 13000
- produceGroupId: produce_group-002
  grade: ResultGrade_SPlus
  threshold: 14500
- produceGroupId: produce_group-002
  grade: ResultGrade_Ss
  threshold: 16000
- produceGroupId: produce_group-002
  grade: ResultGrade_SsPlus
  threshold: 18000
- produceGroupId: produce_group-002
  grade: ResultGrade_Sss
  threshold: 20000
- produceGroupId: produce_group-002
  grade: ResultGrade_SssPlus
  threshold: 23000