- id: producer_ranking_produce-000
  produceId: produce-004
- id: producer_ranking_produce-000
  produceId: produce-005
- id: producer_ranking_produce-001
  produceId: produce-004
- id: producer_ranking_produce-001
  produceId: produce-005
- id: producer_ranking_produce-001
  produceId: produce-006
- id: producer_ranking_produce-002
  produceId: produce-004
- id: producer_ranking_produce-002
  produceId: produce-005
- id: producer_ranking_produce-002
  produceId: produce-006
- id: producer_ranking_produce-003
  produceId: produce-004
- id: producer_ranking_produce-003
  produceId: produce-005
- id: producer_ranking_produce-003
  produceId: produce-006
- id: producer_ranking_produce-003
  produceId: produce-008
- id: producer_ranking_produce-004
  produceId: produce-004
- id: producer_ranking_produce-004
  produceId: produce-005
- id: producer_ranking_produce-004
  produceId: produce-006
- id: producer_ranking_produce-004
  produceId: produce-008