- produceId: produce-003
  characterId: amao
  unlockConditionSetId: cd-dearness_level-amao-10
- produceId: produce-003
  characterId: atbm
  unlockConditionSetId: cd-dearness_level-atbm-10
- produceId: produce-003
  characterId: fktn
  unlockConditionSetId: cd-dearness_level-fktn-10
- produceId: produce-003
  characterId: hmsz
  unlockConditionSetId: cd-dearness_level-hmsz-10
- produceId: produce-003
  characterId: hrnm
  unlockConditionSetId: cd-dearness_level-hrnm-10
- produceId: produce-003
  characterId: hski
  unlockConditionSetId: cd-dearness_level-hski-10
- produceId: produce-003
  characterId: hume
  unlockConditionSetId: cd-dearness_level-hume-10
- produceId: produce-003
  characterId: jsna
  unlockConditionSetId: cd-dearness_level-jsna-10
- produceId: produce-003
  characterId: kcna
  unlockConditionSetId: cd-dearness_level-kcna-10
- produceId: produce-003
  characterId: kllj
  unlockConditionSetId: cd-dearness_level-kllj-10
- produceId: produce-003
  characterId: shro
  unlockConditionSetId: cd-dearness_level-shro-10
- produceId: produce-003
  characterId: ssmk
  unlockConditionSetId: cd-dearness_level-ssmk-10
- produceId: produce-003
  characterId: ttmr
  unlockConditionSetId: cd-dearness_level-ttmr-10
- produceId: produce-005
  characterId: amao
  unlockConditionSetId: cd-dearness_level-amao-20
- produceId: produce-005
  characterId: atbm
  unlockConditionSetId: cd-dearness_level-atbm-20
- produceId: produce-005
  characterId: fktn
  unlockConditionSetId: cd-dearness_level-fktn-20
- produceId: produce-005
  characterId: hmsz
  unlockConditionSetId: cd-dearness_level-hmsz-20
- produceId: produce-005
  characterId: hrnm
  unlockConditionSetId: cd-dearness_level-hrnm-20
- produceId: produce-005
  characterId: hski
  unlockConditionSetId: cd-dearness_level-hski-20
- produceId: produce-005
  characterId: hume
  unlockConditionSetId: cd-dearness_level-hume-20
- produceId: produce-005
  characterId: jsna
  unlockConditionSetId: cd-dearness_level-jsna-20
- produceId: produce-005
  characterId: kcna
  unlockConditionSetId: cd-dearness_level-kcna-20
- produceId: produce-005
  characterId: kllj
  unlockConditionSetId: cd-dearness_level-kllj-20
- produceId: produce-005
  characterId: shro
  unlockConditionSetId: cd-dearness_level-shro-20
- produceId: produce-005
  characterId: ssmk
  unlockConditionSetId: cd-dearness_level-ssmk-20
- produceId: produce-005
  characterId: ttmr
  unlockConditionSetId: cd-dearness_level-ttmr-20
- produceId: produce-006
  characterId: amao
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open
- produceId: produce-006
  characterId: atbm
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open
- produceId: produce-006
  characterId: fktn
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open
- produceId: produce-006
  characterId: hmsz
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open
- produceId: produce-006
  characterId: hrnm
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open
- produceId: produce-006
  characterId: hski
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open
- produceId: produce-006
  characterId: hume
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open
- produceId: produce-006
  characterId: jsna
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open
- produceId: produce-006
  characterId: kcna
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open
- produceId: produce-006
  characterId: kllj
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open
- produceId: produce-006
  characterId: shro
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open
- produceId: produce-006
  characterId: ssmk
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open
- produceId: produce-006
  characterId: ttmr
  unlockConditionSetId: cd-hajime_legend_produce-unlock_open