- produceId: produce-001
  examEffectType: ProduceExamEffectType_ExamParameterBuff
  examInitialDeckId: initial_deck-produce_default-parameter_buff
- produceId: produce-001
  examEffectType: ProduceExamEffectType_ExamLessonBuff
  examInitialDeckId: initial_deck-produce_default-lesson_buff
- produceId: produce-001
  examEffectType: ProduceExamEffectType_ExamReview
  examInitialDeckId: initial_deck-produce_default-review
- produceId: produce-001
  examEffectType: ProduceExamEffectType_ExamCardPlayAggressive
  examInitialDeckId: initial_deck-produce_default-aggressive
- produceId: produce-001
  examEffectType: ProduceExamEffectType_ExamConcentration
  examInitialDeckId: initial_deck-produce_default-concentration
- produceId: produce-001
  examEffectType: ProduceExamEffectType_ExamFullPower
  examInitialDeckId: initial_deck-produce_default-full_power
- produceId: produce-002
  examEffectType: ProduceExamEffectType_ExamParameterBuff
  examInitialDeckId: initial_deck-produce_default-parameter_buff
- produceId: produce-002
  examEffectType: ProduceExamEffectType_ExamLessonBuff
  examInitialDeckId: initial_deck-produce_default-lesson_buff
- produceId: produce-002
  examEffectType: ProduceExamEffectType_ExamReview
  examInitialDeckId: initial_deck-produce_default-review
- produceId: produce-002
  examEffectType: ProduceExamEffectType_ExamCardPlayAggressive
  examInitialDeckId: initial_deck-produce_default-aggressive
- produceId: produce-002
  examEffectType: ProduceExamEffectType_ExamConcentration
  examInitialDeckId: initial_deck-produce_default-concentration
- produceId: produce-002
  examEffectType: ProduceExamEffectType_ExamFullPower
  examInitialDeckId: initial_deck-produce_default-full_power
- produceId: produce-003
  examEffectType: ProduceExamEffectType_ExamParameterBuff
  examInitialDeckId: initial_deck-produce_default-parameter_buff
- produceId: produce-003
  examEffectType: ProduceExamEffectType_ExamLessonBuff
  examInitialDeckId: initial_deck-produce_default-lesson_buff
- produceId: produce-003
  examEffectType: ProduceExamEffectType_ExamReview
  examInitialDeckId: initial_deck-produce_default-review
- produceId: produce-003
  examEffectType: ProduceExamEffectType_ExamCardPlayAggressive
  examInitialDeckId: initial_deck-produce_default-aggressive
- produceId: produce-003
  examEffectType: ProduceExamEffectType_ExamConcentration
  examInitialDeckId: initial_deck-produce_default-concentration
- produceId: produce-003
  examEffectType: ProduceExamEffectType_ExamFullPower
  examInitialDeckId: initial_deck-produce_default-full_power
- produceId: produce-004
  examEffectType: ProduceExamEffectType_ExamParameterBuff
  examInitialDeckId: initial_deck-produce_default-parameter_buff
- produceId: produce-004
  examEffectType: ProduceExamEffectType_ExamLessonBuff
  examInitialDeckId: initial_deck-produce_default-lesson_buff
- produceId: produce-004
  examEffectType: ProduceExamEffectType_ExamReview
  examInitialDeckId: initial_deck-produce_default-review
- produceId: produce-004
  examEffectType: ProduceExamEffectType_ExamCardPlayAggressive
  examInitialDeckId: initial_deck-produce_default-aggressive
- produceId: produce-004
  examEffectType: ProduceExamEffectType_ExamConcentration
  examInitialDeckId: initial_deck-produce_default-concentration
- produceId: produce-004
  examEffectType: ProduceExamEffectType_ExamFullPower
  examInitialDeckId: initial_deck-produce_default-full_power
- produceId: produce-005
  examEffectType: ProduceExamEffectType_ExamParameterBuff
  examInitialDeckId: initial_deck-produce_default-parameter_buff
- produceId: produce-005
  examEffectType: ProduceExamEffectType_ExamLessonBuff
  examInitialDeckId: initial_deck-produce_default-lesson_buff
- produceId: produce-005
  examEffectType: ProduceExamEffectType_ExamReview
  examInitialDeckId: initial_deck-produce_default-review
- produceId: produce-005
  examEffectType: ProduceExamEffectType_ExamCardPlayAggressive
  examInitialDeckId: initial_deck-produce_default-aggressive
- produceId: produce-005
  examEffectType: ProduceExamEffectType_ExamConcentration
  examInitialDeckId: initial_deck-produce_default-concentration
- produceId: produce-005
  examEffectType: ProduceExamEffectType_ExamFullPower
  examInitialDeckId: initial_deck-produce_default-full_power
- produceId: produce-006
  examEffectType: ProduceExamEffectType_ExamParameterBuff
  examInitialDeckId: initial_deck-produce_006-parameter_buff
- produceId: produce-006
  examEffectType: ProduceExamEffectType_ExamLessonBuff
  examInitialDeckId: initial_deck-produce_006-lesson_buff
- produceId: produce-006
  examEffectType: ProduceExamEffectType_ExamReview
  examInitialDeckId: initial_deck-produce_006-review
- produceId: produce-006
  examEffectType: ProduceExamEffectType_ExamCardPlayAggressive
  examInitialDeckId: initial_deck-produce_006-card_play_aggressive
- produceId: produce-006
  examEffectType: ProduceExamEffectType_ExamConcentration
  examInitialDeckId: initial_deck-produce_006-concentration
- produceId: produce-006
  examEffectType: ProduceExamEffectType_ExamFullPower
  examInitialDeckId: initial_deck-produce_006-full_power