- id: producer_ranking_rank_grade_season-000
  upperLimitRank: 1
  grade: ProducerRankingGrade_RainbowPlus
- id: producer_ranking_rank_grade_season-000
  upperLimitRank: 101
  grade: ProducerRankingGrade_Rainbow
- id: producer_ranking_rank_grade_season-000
  upperLimitRank: 1001
  grade: ProducerRankingGrade_Gold
- id: producer_ranking_rank_grade_season-000
  upperLimitRank: 3001
  grade: ProducerRankingGrade_Silver
- id: producer_ranking_rank_grade_season-000
  upperLimitRank: 5001
  grade: ProducerRankingGrade_Bronze
- id: producer_ranking_rank_grade_season-000
  upperLimitRank: 10001
  grade: ProducerRankingGrade_Normal