- id: challenge_slot-exam_card_play_aggressive-produce_003-group_001
  produceItemId: pitem_00-1-025-challenge
  lessonLimitUpScore: 5
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_001
  produceItemId: pitem_00-1-026-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_001
  produceItemId: pitem_00-1-027-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_001
  produceItemId: pitem_02-1-031-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_001
  produceItemId: pitem_02-1-032-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_001
  produceItemId: pitem_02-2-057-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_001
  produceItemId: pitem_02-2-062-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_001
  produceItemId: pitem_02-2-063-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_002
  produceItemId: pitem_00-1-028-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_002
  produceItemId: pitem_00-2-039-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_002
  produceItemId: pitem_00-2-040-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_002
  produceItemId: pitem_02-2-059-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_002
  produceItemId: pitem_02-2-064-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_002
  produceItemId: pitem_02-2-065-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_002
  produceItemId: pitem_02-2-066-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_003
  produceItemId: pitem_00-2-041-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_003
  produceItemId: pitem_00-2-042-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_003
  produceItemId: pitem_00-2-043-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_003
  produceItemId: pitem_02-2-067-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_003
  produceItemId: pitem_02-3-085-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_003
  produceItemId: pitem_02-3-086-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_card_play_aggressive-produce_003-group_003
  produceItemId: pitem_02-3-087-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_concentration-produce_003-group_001
  produceItemId: pitem_00-1-025-challenge
  lessonLimitUpScore: 5
- id: challenge_slot-exam_concentration-produce_003-group_001
  produceItemId: pitem_00-1-026-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_concentration-produce_003-group_001
  produceItemId: pitem_00-1-027-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_concentration-produce_003-group_001
  produceItemId: pitem_03-1-033-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_concentration-produce_003-group_001
  produceItemId: pitem_03-1-034-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_concentration-produce_003-group_001
  produceItemId: pitem_03-2-068-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_concentration-produce_003-group_001
  produceItemId: pitem_03-2-069-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_concentration-produce_003-group_001
  produceItemId: pitem_03-2-075-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_concentration-produce_003-group_002
  produceItemId: pitem_00-1-028-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_concentration-produce_003-group_002
  produceItemId: pitem_00-2-039-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_concentration-produce_003-group_002
  produceItemId: pitem_00-2-040-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_concentration-produce_003-group_002
  produceItemId: pitem_03-2-070-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_concentration-produce_003-group_002
  produceItemId: pitem_03-2-071-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_concentration-produce_003-group_002
  produceItemId: pitem_03-2-072-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_concentration-produce_003-group_002
  produceItemId: pitem_03-2-077-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_concentration-produce_003-group_003
  produceItemId: pitem_00-2-041-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_concentration-produce_003-group_003
  produceItemId: pitem_00-2-042-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_concentration-produce_003-group_003
  produceItemId: pitem_00-2-043-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_concentration-produce_003-group_003
  produceItemId: pitem_03-2-073-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_concentration-produce_003-group_003
  produceItemId: pitem_03-3-088-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_concentration-produce_003-group_003
  produceItemId: pitem_03-3-089-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_concentration-produce_003-group_003
  produceItemId: pitem_03-3-091-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_full_power-produce_003-group_001
  produceItemId: pitem_00-1-025-challenge
  lessonLimitUpScore: 5
- id: challenge_slot-exam_full_power-produce_003-group_001
  produceItemId: pitem_00-1-026-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_full_power-produce_003-group_001
  produceItemId: pitem_00-1-027-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_full_power-produce_003-group_001
  produceItemId: pitem_03-1-033-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_full_power-produce_003-group_001
  produceItemId: pitem_03-1-034-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_full_power-produce_003-group_001
  produceItemId: pitem_03-2-069-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_full_power-produce_003-group_001
  produceItemId: pitem_03-2-074-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_full_power-produce_003-group_001
  produceItemId: pitem_03-2-075-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_full_power-produce_003-group_002
  produceItemId: pitem_00-1-028-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_full_power-produce_003-group_002
  produceItemId: pitem_00-2-039-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_full_power-produce_003-group_002
  produceItemId: pitem_00-2-040-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_full_power-produce_003-group_002
  produceItemId: pitem_03-2-071-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_full_power-produce_003-group_002
  produceItemId: pitem_03-2-076-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_full_power-produce_003-group_002
  produceItemId: pitem_03-2-077-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_full_power-produce_003-group_002
  produceItemId: pitem_03-2-078-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_full_power-produce_003-group_003
  produceItemId: pitem_00-2-041-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_full_power-produce_003-group_003
  produceItemId: pitem_00-2-042-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_full_power-produce_003-group_003
  produceItemId: pitem_00-2-043-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_full_power-produce_003-group_003
  produceItemId: pitem_03-2-079-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_full_power-produce_003-group_003
  produceItemId: pitem_03-3-089-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_full_power-produce_003-group_003
  produceItemId: pitem_03-3-090-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_full_power-produce_003-group_003
  produceItemId: pitem_03-3-091-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_lesson_buff-produce_003-group_001
  produceItemId: pitem_00-1-025-challenge
  lessonLimitUpScore: 5
- id: challenge_slot-exam_lesson_buff-produce_003-group_001
  produceItemId: pitem_00-1-026-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_lesson_buff-produce_003-group_001
  produceItemId: pitem_00-1-027-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_lesson_buff-produce_003-group_001
  produceItemId: pitem_01-1-029-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_lesson_buff-produce_003-group_001
  produceItemId: pitem_01-1-030-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_lesson_buff-produce_003-group_001
  produceItemId: pitem_01-2-045-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_lesson_buff-produce_003-group_001
  produceItemId: pitem_01-2-050-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_lesson_buff-produce_003-group_001
  produceItemId: pitem_01-2-051-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_lesson_buff-produce_003-group_002
  produceItemId: pitem_00-1-028-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_lesson_buff-produce_003-group_002
  produceItemId: pitem_00-2-039-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_lesson_buff-produce_003-group_002
  produceItemId: pitem_00-2-040-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_lesson_buff-produce_003-group_002
  produceItemId: pitem_01-2-047-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_lesson_buff-produce_003-group_002
  produceItemId: pitem_01-2-052-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_lesson_buff-produce_003-group_002
  produceItemId: pitem_01-2-053-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_lesson_buff-produce_003-group_002
  produceItemId: pitem_01-2-054-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_lesson_buff-produce_003-group_003
  produceItemId: pitem_00-2-041-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_lesson_buff-produce_003-group_003
  produceItemId: pitem_00-2-042-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_lesson_buff-produce_003-group_003
  produceItemId: pitem_00-2-043-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_lesson_buff-produce_003-group_003
  produceItemId: pitem_01-2-055-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_lesson_buff-produce_003-group_003
  produceItemId: pitem_01-3-081-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_lesson_buff-produce_003-group_003
  produceItemId: pitem_01-3-082-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_lesson_buff-produce_003-group_003
  produceItemId: pitem_01-3-083-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_parameter_buff-produce_003-group_001
  produceItemId: pitem_00-1-025-challenge
  lessonLimitUpScore: 5
- id: challenge_slot-exam_parameter_buff-produce_003-group_001
  produceItemId: pitem_00-1-026-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_parameter_buff-produce_003-group_001
  produceItemId: pitem_00-1-027-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_parameter_buff-produce_003-group_001
  produceItemId: pitem_01-1-029-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_parameter_buff-produce_003-group_001
  produceItemId: pitem_01-1-030-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_parameter_buff-produce_003-group_001
  produceItemId: pitem_01-2-044-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_parameter_buff-produce_003-group_001
  produceItemId: pitem_01-2-045-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_parameter_buff-produce_003-group_001
  produceItemId: pitem_01-2-051-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_parameter_buff-produce_003-group_002
  produceItemId: pitem_00-1-028-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_parameter_buff-produce_003-group_002
  produceItemId: pitem_00-2-039-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_parameter_buff-produce_003-group_002
  produceItemId: pitem_00-2-040-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_parameter_buff-produce_003-group_002
  produceItemId: pitem_01-2-046-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_parameter_buff-produce_003-group_002
  produceItemId: pitem_01-2-047-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_parameter_buff-produce_003-group_002
  produceItemId: pitem_01-2-048-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_parameter_buff-produce_003-group_002
  produceItemId: pitem_01-2-053-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_parameter_buff-produce_003-group_003
  produceItemId: pitem_00-2-041-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_parameter_buff-produce_003-group_003
  produceItemId: pitem_00-2-042-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_parameter_buff-produce_003-group_003
  produceItemId: pitem_00-2-043-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_parameter_buff-produce_003-group_003
  produceItemId: pitem_01-2-049-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_parameter_buff-produce_003-group_003
  produceItemId: pitem_01-3-080-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_parameter_buff-produce_003-group_003
  produceItemId: pitem_01-3-081-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_parameter_buff-produce_003-group_003
  produceItemId: pitem_01-3-083-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_review-produce_003-group_001
  produceItemId: pitem_00-1-025-challenge
  lessonLimitUpScore: 5
- id: challenge_slot-exam_review-produce_003-group_001
  produceItemId: pitem_00-1-026-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_review-produce_003-group_001
  produceItemId: pitem_00-1-027-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_review-produce_003-group_001
  produceItemId: pitem_02-1-031-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_review-produce_003-group_001
  produceItemId: pitem_02-1-032-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_review-produce_003-group_001
  produceItemId: pitem_02-2-056-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_review-produce_003-group_001
  produceItemId: pitem_02-2-057-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_review-produce_003-group_001
  produceItemId: pitem_02-2-063-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_review-produce_003-group_002
  produceItemId: pitem_00-1-028-challenge
  lessonLimitUpScore: 10
- id: challenge_slot-exam_review-produce_003-group_002
  produceItemId: pitem_00-2-039-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_review-produce_003-group_002
  produceItemId: pitem_00-2-040-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_review-produce_003-group_002
  produceItemId: pitem_02-2-058-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_review-produce_003-group_002
  produceItemId: pitem_02-2-059-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_review-produce_003-group_002
  produceItemId: pitem_02-2-060-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_review-produce_003-group_002
  produceItemId: pitem_02-2-065-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_review-produce_003-group_003
  produceItemId: pitem_00-2-041-challenge
  lessonLimitUpScore: 15
- id: challenge_slot-exam_review-produce_003-group_003
  produceItemId: pitem_00-2-042-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_review-produce_003-group_003
  produceItemId: pitem_00-2-043-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_review-produce_003-group_003
  produceItemId: pitem_02-2-061-challenge
  lessonLimitUpScore: 20
- id: challenge_slot-exam_review-produce_003-group_003
  produceItemId: pitem_02-3-084-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_review-produce_003-group_003
  produceItemId: pitem_02-3-085-challenge
  lessonLimitUpScore: 25
- id: challenge_slot-exam_review-produce_003-group_003
  produceItemId: pitem_02-3-087-challenge
  lessonLimitUpScore: 25